CREATE TABLE T24_LNMEMO_ACTIVITY_ACC_ECB
(
    WINDOW_ID NUMBER(25),
    CONSTRAINT PK_T24_LNMEMO_ACTIVITY_ACC_ECB PRIMARY KEY (WINDOW_ID)
)
    INMEMORY MEMCOMPRESS FOR QUERY LOW
    PRIORITY CRITICAL
    TABLESPACE T24RAWOGG;
