CREATE TABLE T24_LNMEMO_ACTIVITY_ARR
(
    RECID     VARCHAR2(255),
    WINDOW_ID NUMBER(25)
)
    INMEMORY MEMCOMPRESS FOR QUERY LOW
    PRIORITY CRITICAL
    TABLESPACE T24RAWOGG;

CREATE INDEX IDX_T24_LNMEMO_ACTIVITY_ARR_REC_WIN_ID
    ON T24_LNMEMO_ACTIVITY_ARR (RECID, WINDOW_ID)
    TABLESPACE T24RAWOGG_IDX;

CREATE INDEX IDX_T24_LNMEMO_ACTIVITY_ARR_WINDOW_ID
    ON T24_LNMEMO_ACTIVITY_ARR (WINDOW_ID)
    TABLESPACE T24RAWOGG_IDX;
