CREATE TABLE T24_LNMEMO_ACTIVITY_BIL
(
    RECID          VARCHAR2(255),
    WINDOW_ID      NUMBER(25),
    ARRANGEMENT_ID VARCHAR2(255)
)
    INMEMORY MEMCOMPRESS FOR QUERY LOW
    PRIORITY CRITICAL
    TABLESPACE T24RAWOGG;
