CREATE TABLE T24_LNMEMO_ACTIVITY_BIL
(
    WINDOW_ID      NUMBER(25),
    ARRANGEMENT_ID VARCHAR2(255),
    CAPTURED_TIME  TIMESTAMP(3) DEFAULT SYSTIMESTAMP
)
    INMEMORY MEMCOMPRESS FOR QUERY LOW
    PRIORITY CRITICAL
    TABLESPACE T24RAWOGG;
