CREATE TABLE FMSB_ARR_LNMEMO
(
    RECID          VARCHAR2(255),
    WINDOW_ID      NUMBER(25),
    OP_TYPE        CHAR(1),
    COMMIT_TS      TIMESTAMP(3),
    REPLICAT_TS    TIMESTAMP(3),
    MAPPED_TS      TIMESTAMP(3),
    LINKED_APPL_ID VARCHAR2(255),
    CONSTRAINT PK_FMSB_ARR_LNMEMO PRIMARY KEY (RECID)
)
    TABLESPACE T24DB_OGGDS;

CREATE INDEX IDX_FMSB_ARR_LNMEMO_OP_TYPE
    ON FMSB_ARR_LNMEMO (OP_TYPE)
    TABLESPACE T24DB_OGGDS;

CREATE INDEX IDX_FMSB_ARR_LNMEMO_WINDOW_ID
    ON FMSB_ARR_LNMEMO (WINDOW_ID)
    TABLESPACE T24DB_OGGDS;

CREATE INDEX IDX_FMSB_ARR_LNMEMO_REC_WIN_ID
    ON FMSB_ARR_LNMEMO (RECID, WINDOW_ID)
    TABLESPACE T24DB_OGGDS;

CREATE INDEX IDX_FMSB_ARR_LNMEMO_LINKED_APPL_ID
    ON FMSB_ARR_LNMEMO (LINKED_APPL_ID)
    TABLESPACE T24DB_OGGDS;
