CREATE TABLE FMSB_BIL_LNMEMO
(
    RECID          VARCHAR2(255),
    WINDOW_ID      NUMBER(25),
    OP_TYPE        CHAR(1),
    COMMIT_TS      TIMESTAMP(3),
    REPLICAT_TS    TIMESTAMP(3),
    MAPPED_TS      TIMESTAMP(3),
    ARRANGEMENT_ID VARCHAR2(255),
    BILPRN_AMT     NUMBER(15, 2),
    BILINT_AMT     NUMBER(15, 2),
    BILLC_AMT      NUMBER(15, 2),
    CONSTRAINT PK_FMSB_BIL_LNMEMO PRIMARY KEY (RECID)
)
    TABLESPACE T24RAWOGG;

CREATE INDEX IDX_FMSB_BIL_LNMEMO_OP_TYPE
    ON FMSB_BIL_LNMEMO (OP_TYPE)
    TABLESPACE T24RAWOGG_IDX;

CREATE INDEX IDX_FMSB_BIL_LNMEMO_WINDOW_ID
    ON FMSB_BIL_LNMEMO (WINDOW_ID)
    TABLESPACE T24RAWOGG_IDX;

CREATE INDEX IDX_FMSB_BIL_LNMEMO_REC_WIN_ID
    ON FMSB_BIL_LNMEMO (RECID, WINDOW_ID)
    TABLESPACE T24RAWOGG_IDX;

CREATE INDEX IDX_FMSB_BIL_LNMEMO_ARRANGEMENT_ID
    ON FMSB_BIL_LNMEMO (ARRANGEMENT_ID)
    TABLESPACE T24RAWOGG_IDX;
