CREATE MATERIALIZED VIEW LOG ON FMSB_CHG_MAPPED
TABLESPACE T24RAWSTAGEUAT
WITH ROWID, SEQUENCE (ID_COMP_1, ID_COMP_3)
INCLUDING NEW VALUES;

CREATE MATERIALIZED VIEW MV_FMSB_CHG_CDTNEW
TABLESPACE T24RAWSTAGEUAT
NOLOGGING
CACHE
BUILD IMMEDIATE
REFRESH FAST ON COMMIT
AS
SELECT 
    ID_COMP_1,
    MAX(ID_COMP_3) AS MAX_ID_COMP_3
FROM 
    FMSB_CHG_MAPPED
GROUP BY 
    ID_COMP_1;

CREATE UNIQUE INDEX IDX_MV_CHG_CDTNEW_ID_COMP_1 
ON MV_FMSB_CHG_CDTNEW (ID_COMP_1)
TABLESPACE T24RAWSTAGEUAT;