CREATE GLOBAL TEMPORARY TABLE TMP_INFLIGHT_RECORD
(
    JOIN_KEY  VARCHAR2(255),
    WINDOW_ID NUMBER(25)
) ON COMMIT DELETE ROWS;

CREATE INDEX IX_TMP_INFLIGHT_RECORD_JOIN_KEY
    ON TMP_INFLIGHT_RECORD (JOIN_KEY);

CREATE INDEX IX_TMP_INFLIGHT_RECORD_WINDOW_ID
    ON TMP_INFLIGHT_RECORD (WINDOW_ID);
