CREATE TABLE FMSB_AIT_CDTNEW
(
    RECID          VARCHAR2(255),
    WINDOW_ID      NUMBER(25),
    OP_TYPE        CHAR(1),
    COMMIT_TS      TIMESTAMP(3),
    REPLICAT_TS    TIMESTAMP(3),
    MAPPED_TS      TIMESTAMP(3),
    ID_COMP_1      VARCHAR2(255),
    ID_COMP_2      VARCHAR2(255),
    ID_COMP_3      VARCHAR2(255),
    EFFECTIVE_RATE VARCHAR2(255),
    CONSTRAINT PK_FMSB_AIT_CDTNEW PRIMARY KEY (RECID)
)
    TABLESPACE T24RAWOGG;

CREATE INDEX IDX_FMSB_AIT_CDTNEW_OP_TYPE
    ON FMSB_AIT_CDTNEW (OP_TYPE)
    TABLESPACE T24RAWOGG_IDX;

CREATE INDEX IDX_FMSB_AIT_CDTNEW_WINDOW_ID
    ON FMSB_AIT_CDTNEW (WINDOW_ID)
    TABLESPACE T24RAWOGG_IDX;

CREATE INDEX IDX_FMSB_AIT_CDTNEW_REC_WIN_ID
    ON FMSB_AIT_CDTNEW (RECID, WINDOW_ID)
    TABLESPACE T24RAWOGG_IDX;

CREATE INDEX IDX_FMSB_AIT_CDTNEW_ID_COMP_1_ID_COMP_3_DESC
    ON FMSB_AIT_CDTNEW (ID_COMP_1, ID_COMP_3 DESC)
    TABLESPACE T24RAWOGG_IDX;