CREATE TABLE FMSB_ARR_CD
(
    RECID              VARCHAR2(255),
    WINDOW_ID          NUMBER(25),
    COMMIT_TS          TIMESTAMP(3),
    REPLICAT_TS        TIMESTAMP(3),
    MAPPED_TS          TIMESTAMP(3),
    ACTIVE_PRODUCT     VARCHAR2(255),
    ARR_STATUS         VARCHAR2(255),
    CURRENCY           VARCHAR2(5),
    LINKED_APPL_ID     VARCHAR2(255),
    ORIG_CONTRACT_DATE DATE,
    START_DATE         DATE,
    CONSTRAINT PK_FMSB_ARR_CD PRIMARY KEY (RECID)
)
    TABLESPACE T24DB_OGGDS;

CREATE INDEX IDX_FMSB_ARR_CD_REC_WIN_ID
    ON FMSB_ARR_CD (RECID, WINDOW_ID)
    TABLESPACE T24DB_OGGDS;

CREATE INDEX IDX_FMSB_ARR_CD_MAPPED_WINDOW_ID
    ON FMSB_ARR_CD (WINDOW_ID)
    TABLESPACE T24DB_OGGDS;

CREATE INDEX IDX_FMSB_ARR_CD_LINKED_APPL_ID
    ON FMSB_ARR_CD (LINKED_APPL_ID)
    TABLESPACE T24DB_OGGDS;