
CREATE TABLE F_POR_TMTRAN
(
    RECID            VARCHAR2(255),
    WINDOW_ID        NUMBER(25),
    OP_TYPE          VARCHAR2(10),
    COMMIT_TS        TIMESTAMP(3),
    REPLICAT_TS      TIMESTAMP(3),
    MAPPED_TS        TIMESTAMP(3),
   OUTPUT_CHANNEL     VARCHAR2(255),
STATUS_CODE    VARCHAR2(255),
    CONSTRAINT PK_F_POR_TMTRAN PRIMARY KEY (RECID)
)
    TABLESPACE T24RAWOGG;

CREATE INDEX "IDX_F_POR_TMTRAN_OP_TYPE" ON "F_POR_TMTRAN" ("OP_TYPE") 
    PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
    TABLESPACE "T24RAWOGG_IDX" ;