CREATE TABLE F_SUP_TMTRAN
(
    RECID            VARCHAR2(255),
    WINDOW_ID        NUMBER(25),
    OP_TYPE          VARCHAR2(10),
    COMMIT_TS        TIMESTAMP(3),
    REPLICAT_TS      TIMESTAMP(3),
    MAPPED_TS        TIMESTAMP(3),
   
LOC_FIELD_NAME        VARCHAR2(255),
LOC_FIELD_NAME_M    VARCHAR2(255),
LOC_FIELD_VALUE_M   VARCHAR2(255),
LOC_FIELD_VALUE_S   VARCHAR2(255),
LOC_FIELD_VALUE VARCHAR2(255),

    CONSTRAINT PK_F_SUP_TMTRAN PRIMARY KEY (RECID)
)
    TABLESPACE T24RAWOGG;

CREATE INDEX "IDX_F_SUP_TMTRAN_OP_TYPE" ON "F_SUP_TMTRAN" ("OP_TYPE") 
      PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
      TABLESPACE "T24RAWOGG_IDX" ;