CREATE TABLE F_TMV_TMTRAN
(
    RECID            VARCHAR2(255),
    WINDOW_ID        NUMBER(25),
    OP_TYPE          VARCHAR2(10),
    COMMIT_TS        TIMESTAMP(3),
    REPLICAT_TS      TIMESTAMP(3),
    MAPPED_TS        TIMESTAMP(3),
  
ORIGINALFTNUMBER  VARCHAR2(255),
RESERVED1   VARCHAR2(255),
RESERVED2   VARCHAR2(255),
PAYMENTDIRECTION    VARCHAR2(255),
    CONSTRAINT PK_F_TMV_TMTRAN PRIMARY KEY (RECID)
)
    TABLESPACE T24RAWOGG;

CREATE INDEX "IDX_F_TMV_TMTRAN_OP_TYPE" ON "F_TMV_TMTRAN" ("OP_TYPE") 
      PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
      TABLESPACE "T24RAWOGG_IDX" ;