CREATE TABLE FMSB_STM_TMTRAN
(
    RECID            VARCHAR2(255),
    WINDOW_ID        NUMBER(25),
    OP_TYPE          VARCHAR2(10),
    COMMIT_TS        TIMESTAMP(3),
    REPLICAT_TS      TIMESTAMP(3),
    MAPPED_TS        TIMESTAMP(3),
    ACCOUNT_NUMBER   VARCHAR2(255),
    AMOUNT_FCY       VARCHAR2(255),
    AMOUNT_LCY       VARCHAR2(255),
    BOOKING_DATE     VARCHAR2(8),
    CRF_TYPE         VARCHAR2(255),
    CURRENCY         VARCHAR2(4),
    DATE_TIME        VARCHAR2(255),
    INPUTTER         VARCHAR2(255),
    NARRATIVE_1      VARCHAR2(255),
    NARRATIVE        VARCHAR2(1000),
    OUR_REFERENCE    VARCHAR2(255),
    PRODUCT_CATEGORY VARCHAR2(10),
    RECORD_STATUS    VARCHAR2(255),
    REVERSAL_MARKER  VARCHAR2(255),
    SYSTEM_ID        VARCHAR2(10),
    TRANS_REFERENCE  VARCHAR2(255),
    THEIR_REFERENCE varchar2(255),
    TRANSACTION_CODE VARCHAR2(10),
    VALUE_DATE       VARCHAR2(8),
    CONSTRAINT PK_FMSB_STM_TMTRAN PRIMARY KEY (RECID)
)
    TABLESPACE T24RAWOGG;

    CREATE INDEX "IDX_FMSB_STM_TMTRAN_OP_TYPE" ON "FMSB_STM_TMTRAN" ("OP_TYPE") 
      PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
      TABLESPACE "T24RAWOGG_IDX" ;