CREATE TABLE F_POR_SUPPLEMENTARY000_MAPPED(
    RECID VARCHAR2(255),
    WINDOW_ID NUMBER(25),
    OP_TYPE CHAR(1),
    COMMIT_TS TIMESTAMP(3),
    REPLICAT_TS TIMESTAMP(3),
    MAPPED_TS TIMESTAMP(3),
    LOC_FIELD_NAME VARCHAR2(1000),
    CONSTRAINT F_POR_SUPPLEMENTARY000_MAPPED PRIMARY KEY (RECID)
)