CREATE TABLE FMSB_ARC_DDMEMO
(
    RECID          VARCHAR2(255),
    WINDOW_ID      NUMBER(25),
    OP_TYPE        CHAR(1),
    COMMIT_TS      TIMESTAMP(3),
    REPLICAT_TS    TIMESTAMP(3),
    MAPPED_TS      TIMESTAMP(3),
    ARRANGEMENT    VARCHAR2(255),
    EFFECTIVE_DATE DATE,
    CONSTRAINT PK_FMSB_ARC_DDMEMO PRIMARY KEY (RECID)
)
    TABLESPACE T24RAWOGG;

CREATE INDEX IDX_FMSB_ARC_DDMEMO_OP_TYPE
    ON FMSB_ARC_DDMEMO (OP_TYPE)
    TABLESPACE T24RAWOGG_IDX;

CREATE INDEX IDX_FMSB_ARC_DDMEMO_ARR_EFF_DAT_DESC
    ON FMSB_ARC_DDMEMO (ARRANGEMENT, EFFECTIVE_DATE DESC)
    TABLESPACE T24RAWOGG_IDX;