CREATE TABLE T24_CDMEMO_ACTIVITY_ADL
(
    RECID     VARCHAR2(255),
    WINDOW_ID NUMBER(25)
)
    INMEMORY MEMCOMPRESS FOR QUERY LOW
    PRIORITY CRITICAL
    TABLESPACE T24RAWOGG;

CREATE INDEX IDX_T24_CDMEMO_ACTIVITY_ADL_REC_WIN_ID 
    ON T24_CDMEMO_ACTIVITY_ADL (RECID, WINDOW_ID)
    TABLESPACE T24RAWOGG_IDX;

CREATE INDEX IDX_T24_CDMEMO_ACTIVITY_ADL_WINDOW_ID
    ON T24_CDMEMO_ACTIVITY_ADL (WINDOW_ID)
    TABLESPACE T24RAWOGG_IDX;
