CREATE TABLE T24_CDMEMO_ACTIVITY_ECB (
    RECID     VARCHAR2(255),
    WINDOW_ID NUMBER(25)
)
    INMEMORY MEMCOMPRESS FOR QUERY LOW
    PRIORITY CRITICAL
    TABLESPACE T24RAWSTAGEUAT;

CREATE INDEX IDX_T24_CDMEMO_ACTIVITY_ECB_REC_WIN_ID 
    ON T24_CDMEMO_ACTIVITY_ECB (RECID, WINDOW_ID)
    TABLESPACE T24RAWSTAGEUAT;
