CREATE TABLE T24_LNTNEW_ACTIVITY_ARR
(
    RECID     VARCHAR2(255),
    WINDOW_ID NUMBER(25)
)
    INMEMORY MEMCOMPRESS FOR QUERY LOW
    PRIORITY CRITICAL
    TABLESPACE T24DB_OGGDS;

CREATE INDEX IDX_T24_LNTNEW_ACTIVITY_ARR_REC_WIN_ID
    ON T24_LNTNEW_ACTIVITY_ARR (RECID, WINDOW_ID)
    TABLESPACE T24DB_OGGDS;
