CREATE TABLE T24_LNTNEW_ACTIVITY_AIT
(
    RECID     VARCHAR2(255),
    WINDOW_ID NUMBER(25)
)
    INMEMORY MEMCOMPRESS FOR QUERY LOW
    PRIORITY CRITICAL
    TABLESPACE T24RAWOGG;

CREATE INDEX IDX_T24_LNTNEW_ACTIVITY_AIT_REC_WIN_ID
    ON T24_LNTNEW_ACTIVITY_AIT (RECID, WINDOW_ID)
    TABLESPACE T24RAWOGG_IDX;
