CREATE TABLE T24_LNTNEW_ACTIVITY_ARR_AIT_ASC_AAC_ATA
(
    JOIN_KEY  VARCHAR2(255),
    WINDOW_ID NUMBER(25),
    CAPTURED_TIME TIMESTAMP(3) DEFAULT SYSTIMESTAMP
)
    INMEMORY MEMCOMPRESS FOR QUERY LOW
    PRIORITY CRITICAL
    TABLESPACE T24RAWOGG;