CREATE TABLE T24_LNTNEW_ACTIVITY_ARR_AIT_ASC_AAC
(
    WINDOW_ID NUMBER(25),
    CONSTRAINT PK_T24_LNTNEW_ACTIVITY_ARR_AIT_ASC_AAC PRIMARY KEY (WINDOW_ID)
)
    INMEMORY MEMCOMPRESS FOR QUERY LOW
    PRIORITY CRITICAL
    TABLESPACE T24RAWOGG;