CREATE TABLE T24_LNTNEW_ACTIVITY_ASC
(
    RECID     VARCHAR2(255),
    WINDOW_ID NUMBER(25)
)
    INMEMORY MEMCOMPRESS FOR QUERY LOW
    PRIORITY CRITICAL
    TABLESPACE T24DB_OGGDS;

CREATE INDEX IDX_T24_LNTNEW_ACTIVITY_ASC_REC_WIN_ID
    ON T24_LNTNEW_ACTIVITY_ASC (RECID, WINDOW_ID)
    TABLESPACE T24DB_OGGDS;
