CREATE MATERIALIZED VIEW LOG ON FMSB_ARC_LNTNEW
TABLESPACE T24RAWOGG
WITH ROWID, SEQUENCE (ARRANGEMENT, EFFECTIVE_DATE)
INCLUDING NEW VALUES;

CREATE MATERIALIZED VIEW MV_FMSB_ARC_LNTNEW
TABLESPACE T24RAWOGG
NOLOGGING
CACHE
BUILD IMMEDIATE
REFRESH FAST ON COMMIT
AS
SELECT 
    ARRANGEMENT,
    MIN(EFFECTIVE_DATE) AS MIN_EFF_DAT
FROM 
    FMSB_ARC_LNTNEW
GROUP BY 
    ARRANGEMENT;

CREATE UNIQUE INDEX IDX_MV_FMSB_ARC_LNTNEW_ARRANGEMENT 
ON MV_FMSB_ARC_LNTNEW (ARRANGEMENT)
TABLESPACE T24RAWOGG;