CREATE TABLE FMSB_ARR_CD
(
    RECID              VARCHAR2(255),
    WINDOW_ID          NUMBER(25),
    OP_TYPE            CHAR(1),
    COMMIT_TS          TIMESTAMP(3),
    REPLICAT_TS        TIMESTAMP(3),
    MAPPED_TS          TIMESTAMP(3),
    ACTIVE_PRODUCT     VARCHAR2(255),
    ARR_STATUS         VARCHAR2(255),
    LINKED_APPL_ID     VARCHAR2(255),
    START_DATE         DATE,
    CONSTRAINT PK_FMSB_ARR_CD PRIMARY KEY (RECID)
)
    TABLESPACE T24RAWOGG;

CREATE INDEX IDX_FMSB_ARR_CD_OP_TYPE
    ON FMSB_ARR_CD (OP_TYPE)
    TABLESPACE T24RAWOGG_IDX;

CREATE INDEX IDX_FMSB_ARR_CD_WINDOW_ID
    ON FMSB_ARR_CD (WINDOW_ID)
    TABLESPACE T24RAWOGG_IDX;

CREATE INDEX IDX_FMSB_ARR_CD_REC_WIN_ID
    ON FMSB_ARR_CD (RECID, WINDOW_ID)
    TABLESPACE T24RAWOGG_IDX;

CREATE INDEX IDX_FMSB_ARR_CD_LINKED_APPL_ID
    ON FMSB_ARR_CD (LINKED_APPL_ID)
    TABLESPACE T24RAWOGG_IDX;