CREATE TABLE FMSB_ARC_LNTNEW
(
    RECID          VARCHAR2(255),
    WINDOW_ID      NUMBER(25),
    OP_TYPE        CHAR(1),
    COMMIT_TS      TIMESTAMP(3),
    REPLICAT_TS    TIMESTAMP(3),
    MAPPED_TS      TIMESTAMP(3),
    ARRANGEMENT    VARCHAR2(255),
    EFFECTIVE_DATE DATE,
    CONSTRAINT PK_FMSB_ARC_LNTNEW PRIMARY KEY (RECID)
)
    TABLESPACE T24DB_OGGDS;

CREATE INDEX IDX_FMSB_ARC_LNTNEW_OP_TYPE
    ON FMSB_ARC_LNTNEW (OP_TYPE)
    TABLESPACE T24DB_OGGDS;

CREATE INDEX IDX_FMSB_ARC_LNTNEW_ARR_EFF_DAT
    ON FMSB_ARC_LNTNEW (ARRANGEMENT, EFFECTIVE_DATE)
    TABLESPACE T24DB_OGGDS;
