CREATE TABLE FMSB_ARR_LNTNEW
(
    RECID              VARCHAR2(255),
    WINDOW_ID          NUMBER(25),
    OP_TYPE            CHAR(1),
    COMMIT_TS          TIMESTAMP(3),
    REPLICAT_TS        TIMESTAMP(3),
    MAPPED_TS          TIMESTAMP(3),
    ARR_STATUS         VARCHAR2(50),
    LINKED_APPL_ID     VARCHAR2(255),
    ORIG_CONTRACT_DATE DATE,
    PRODUCT_STATUS     VARCHAR2(1000),
    PRODUCT            VARCHAR2(1000),
    START_DATE         VARCHAR2(8),
    CONSTRAINT PK_FMSB_ARR_LNTNEW PRIMARY KEY (RECID)
)
    TABLESPACE T24RAWOGG;

CREATE INDEX IDX_FMSB_ARR_LNTNEW_OP_TYPE
    ON FMSB_ARR_LNTNEW (OP_TYPE)
    TABLESPACE T24RAWOGG_IDX;

CREATE INDEX IDX_FMSB_ARR_LNTNEW_WINDOW_ID
    ON FMSB_ARR_LNTNEW (WINDOW_ID)
    TABLESPACE T24RAWOGG_IDX;

CREATE INDEX IDX_FMSB_ARR_LNTNEW_REC_WIN_ID
    ON FMSB_ARR_LNTNEW (RECID, WINDOW_ID)
    TABLESPACE T24RAWOGG_IDX;

CREATE INDEX IDX_FMSB_ARR_LNTNEW_LINKED_APPL_ID
    ON FMSB_ARR_LNTNEW (LINKED_APPL_ID)
    TABLESPACE T24RAWOGG_IDX;