CREATE TABLE F_DAT_MAPPED
(
    RECID       VARCHAR2(255),
    WINDOW_ID   NUMBER(25),
    OP_TYPE     CHAR(1),
    COMMIT_TS   TIMESTAMP(3),
    REPLICAT_TS TIMESTAMP(3),
    MAPPED_TS   TIMESTAMP(3),
    TODAY       VARCHAR2(8),
    CONSTRAINT PK_F_DAT_MAPPED PRIMARY KEY (RECID)
)
    INMEMORY MEMCOMPRESS FOR QUERY LOW
    PRIORITY CRITICAL
    TABLESPACE T24RAWOGG;

CREATE INDEX IDX_F_DAT_MAPPED_OP_TYPE
    ON F_DAT_MAPPED (OP_TYPE)
    TABLESPACE T24RAWOGG_IDX;
