CREATE TABLE F_POR_MAPPED
(
    RECID          VARCHAR2(255),
    WINDOW_ID      NUMBER(25),
    OP_TYPE        CHAR(1),
    COMMIT_TS      TIMESTAMP(3),
    REPLICAT_TS    TIMESTAMP(3),
    MAPPED_TS      TIMESTAMP(3),
    STATUS_CODE    VARCHAR2(255),
    OUTPUT_CHANNEL VARCHAR2(255),
    CONSTRAINT PK_F_POR_MAPPED PRIMARY KEY (RECID)
)
    TABLESPACE T24DB_OGGDS;

CREATE INDEX IDX_F_POR_MAPPED_OP_TYPE
    ON F_POR_MAPPED (OP_TYPE)
    TABLESPACE T24DB_OGGDS;
