CREATE TABLE F_POR_MAPPED
(
    RECID          VARCHAR2(255),
    WINDOW_ID      NUMBER(25),
    COMMIT_TS      TIMESTAMP(3),
    REPLICAT_TS    TIMESTAMP(3),
    MAPPED_TS      TIMESTAMP(3),
    STATUS_CODE    VARCHAR2(255),
    OUTPUT_CHANNEL VARCHAR2(255),
    CONSTRAINT PK_F_POR_MAPPED PRIMARY KEY (RECID)
)
    TABLESPACE T24DB_OGGDS;
