CREATE TABLE F_PST_MAPPED
(
    RECID            VARCHAR2(255),
    WINDOW_ID        NUMBER(25),
    OP_TYPE          CHAR(1),
    COMMIT_TS        TIMESTAMP(3),
    REPLICAT_TS      TIMESTAMP(3),
    MAPPED_TS        TIMESTAMP(3),
    RESTRICTION_TYPE VARCHAR2(255),
    CONSTRAINT PK_F_PST_MAPPED PRIMARY KEY (RECID)
)
    INMEMORY MEMCOMPRESS FOR QUERY LOW
    PRIORITY CRITICAL
    TABLESPACE T24DB_OGGDS;
