CREATE TABLE F_SUP_MAPPED
(
    RECID          VARCHAR2(255),
    WINDOW_ID      NUMBER(25),
    OP_TYPE        CHAR(1),
    COMMIT_TS      TIMESTAMP(3),
    REPLICAT_TS    TIMESTAMP(3),
    MAPPED_TS      TIMESTAMP(3),
    LOC_FIELD_NAME CLOB, 
	LOC_FIELD_VALUE CLOB, 
    CONSTRAINT PK_F_SUP_MAPPED PRIMARY KEY (RECID)
)
    TABLESPACE T24RAWOGG;

CREATE INDEX IDX_F_SUP_MAPPED_OP_TYPE
    ON F_SUP_MAPPED (OP_TYPE)
    TABLESPACE T24RAWOGG_IDX;
