CREATE TABLE F_SUP_MAPPED
(
    RECID          VARCHAR2(255),
    WINDOW_ID      NUMBER(25),
    COMMIT_TS      TIMESTAMP(3),
    REPLICAT_TS    TIMESTAMP(3),
    MAPPED_TS      TIMESTAMP(3),
    LOC_FIELD_NAME VARCHAR2(1000),
    CONSTRAINT PK_F_SUP_MAPPED PRIMARY KEY (RECID)
)
    TABLESPACE T24DB_OGGDS;
