CREATE TABLE F_TMV_MAPPED
(
    RECID              VARCHAR2(255),
    WINDOW_ID          NUMBER(25),
    OP_TYPE            CHAR(1),
    COMMIT_TS          TIMESTAMP(3),
    REPLICAT_TS        TIMESTAMP(3),
    MAPPED_TS          TIMESTAMP(3),
    ORIGINAL_FT_NUMBER VARCHAR2(255),
    RESERVED1          VARCHAR2(255),
    RESERVED2          VARCHAR2(255),
    PAYMENT_DIRECTION  VARCHAR2(3),
    CONSTRAINT PK_F_TMV_MAPPED PRIMARY KEY (RECID)
)
    TABLESPACE T24RAWOGG;

CREATE INDEX IDX_F_TMV_MAPPED_OP_TYPE
    ON F_TMV_MAPPED (OP_TYPE)
    TABLESPACE T24RAWOGG_IDX;
