CREATE TABLE FMSB_BIT_MAPPED
(
    RECID         VARCHAR2(255),
    WINDOW_ID     NUMBER(25),
    OP_TYPE       CHAR(1),
    COMMIT_TS     TIMESTAMP(3),
    REPLICAT_TS   TIMESTAMP(3),
    MAPPED_TS     TIMESTAMP(3),
    BCCY          VARCHAR2(255),
    INTEREST_RATE VARCHAR2(255),
    CONSTRAINT PK_FMSB_BIT_MAPPED PRIMARY KEY (RECID)
)
    TABLESPACE T24DB_OGGDS;
