CREATE TABLE FMSB_ASC_MAPPED
(
    RECID        VARCHAR2(255),
    WINDOW_ID    NUMBER(25),
    COMMIT_TS    TIMESTAMP(3),
    REPLICAT_TS  TIMESTAMP(3),
    MAPPED_TS    TIMESTAMP(3),
    ID_COMP_1    VARCHAR2(255),
    ID_COMP_3    VARCHAR2(255),
    BILL_TYPE    VARCHAR2(1000),
    CALC_AMOUNT  VARCHAR2(255),
    PAYMENT_FREQ VARCHAR2(1000),
    PROPERTY     VARCHAR2(1000),
    CONSTRAINT PK_FMSB_ASC_MAPPED PRIMARY KEY (RECID)
)
    TABLESPACE T24DB_OGGDS;
