CREATE TABLE FMSB_FT_MAPPED
(
    RECID           VARCHAR2(255),
    WINDOW_ID       NUMBER(25),
    OP_TYPE         CHAR(1),
    COMMIT_TS       TIMESTAMP(3),
    REPLICAT_TS     TIMESTAMP(3),
    MAPPED_TS       TIMESTAMP(3),
    CHARGES_ACCT_NO VARCHAR2(255),
    MSB_CHANNEL     VARCHAR2(255),
    MSB_TRANS_CODE  VARCHAR2(255),
    MSB_TRANS_SEQ   VARCHAR2(255),
    PAYMENT_DETAILS CLOB,
    CONSTRAINT PK_FMSB_FT_MAPPED PRIMARY KEY (RECID)
)
    TABLESPACE T24RAWOGG;

CREATE INDEX IDX_FMSB_FT_MAPPED_OP_TYPE
    ON FMSB_FT_MAPPED (OP_TYPE)
    TABLESPACE T24RAWOGG_IDX;
