CREATE TABLE FMSB_ARR_MAPPED
(
    RECID              VARCHAR2(255),
    WINDOW_ID          NUMBER(25),
    OP_TYPE            CHAR(1),
    COMMIT_TS          TIMESTAMP(3),
    REPLICAT_TS        TIMESTAMP(3),
    MAPPED_TS          TIMESTAMP(3),
    ACTIVE_PRODUCT     VARCHAR2(255),
    ARR_STATUS         VARCHAR2(255),
    CURRENCY           VARCHAR2(5),
    LINKED_APPL_ID     VARCHAR2(255),
    ORIG_CONTRACT_DATE VARCHAR2(8),
    PRODUCT_LINE       VARCHAR2(1000),
    PRODUCT_STATUS     VARCHAR2(1000),
    PRODUCT            VARCHAR2(1000),
    START_DATE         VARCHAR2(8),
    CONSTRAINT PK_FMSB_ARR_MAPPED PRIMARY KEY (RECID)
)
    TABLESPACE T24RAWOGG;

CREATE INDEX IDX_FMSB_ARR_MAPPED_OP_TYPE
    ON FMSB_ARR_MAPPED (OP_TYPE)
    TABLESPACE T24RAWOGG_IDX;
