CREATE TABLE FMSB_ADL_MAPPED
(
    RECID           VARCHAR2(255),
    WINDOW_ID       NUMBER(25),
    OP_TYPE         CHAR(1),
    COMMIT_TS       TIMESTAMP(3),
    REPLICAT_TS     TIMESTAMP(3),
    MAPPED_TS       TIMESTAMP(3),
    MATURITY_DATE   VARCHAR2(8),
    RENEWAL_DATE    VARCHAR2(8),
    DORMANCY_STATUS VARCHAR2(255),
    CONSTRAINT PK_FMSB_ADL_MAPPED PRIMARY KEY (RECID)
)
    TABLESPACE T24DB_OGGDS;

CREATE INDEX IDX_FMSB_ADL_MAPPED_REC_WIN_ID
    ON FMSB_ADL_MAPPED (RECID, WINDOW_ID)
    TABLESPACE T24DB_OGGDS;
