CREATE TABLE FMSB_TR_MAPPED
(
    RECID       VARCHAR2(255),
    WINDOW_ID   NUMBER(25),
    OP_TYPE     CHAR(1),
    COMMIT_TS   TIMESTAMP(3),
    REPLICAT_TS TIMESTAMP(3),
    MAPPED_TS   TIMESTAMP(3),
    NARRATIVE_1 VARCHAR2(255),
    NARRATIVE_2 VARCHAR2(255),
    CONSTRAINT PK_FMSB_TR_MAPPED PRIMARY KEY (RECID)
)
    TABLESPACE T24RAWOGG;

CREATE INDEX IDX_FMSB_TR_MAPPED_OP_TYPE
    ON FMSB_TR_MAPPED (OP_TYPE)
    TABLESPACE T24RAWOGG_IDX;
