CREATE TABLE FMSB_BIL_MAPPED
(
    RECID          VARCHAR2(255),
    WINDOW_ID      NUMBER(25),
    OP_TYPE        CHAR(1),
    COMMIT_TS      TIMESTAMP(3),
    REPLICAT_TS    TIMESTAMP(3),
    MAPPED_TS      TIMESTAMP(3),
    ARRANGEMENT_ID VARCHAR2(255),
    BILL_TYPE      VARCHAR2(1000),
    BILL_STATUS    VARCHAR2(255),
    OR_PR_AMT      VARCHAR2(500),
    OS_PR_AMT      VARCHAR2(500),
    PAY_PROPERTY   VARCHAR2(1000),
    PAYMENT_TYPE   VARCHAR2(1000),
    CONSTRAINT PK_FMSB_BIL_MAPPED PRIMARY KEY (RECID)
)
    TABLESPACE T24RAWOGG;

CREATE INDEX IDX_FMSB_BIL_MAPPED_OP_TYPE
    ON FMSB_BIL_MAPPED (OP_TYPE)
    TABLESPACE T24RAWOGG_IDX;
