CREATE TABLE FMSB_ARC_MAPPED
(
    RECID          VARCHAR2(255),
    WINDOW_ID      NUMBER(25),
    OP_TYPE        CHAR(1),
    COMMIT_TS      TIMESTAMP(3),
    REPLICAT_TS    TIMESTAMP(3),
    MAPPED_TS      TIMESTAMP(3),
    ARRANGEMENT    VARCHAR2(255),
    ACTIVITY_CLASS VARCHAR2(255),
    ACTIVITY       VARCHAR2(255),
    EFFECTIVE_DATE VARCHAR2(8),
    INPUTTER       VARCHAR2(255),
    CONSTRAINT PK_FMSB_ARC_MAPPED PRIMARY KEY (RECID)
)
    TABLESPACE T24DB_OGGDS;

CREATE INDEX IDX_FMSB_ARC_MAPPED_ARRANGEMENT
    ON FMSB_ARC_MAPPED (ARRANGEMENT)
    TABLESPACE T24DB_OGGDS;
