CREATE TABLE FMSB_ADL_MAPPED
(
    RECID           VARCHAR2(255),
    WINDOW_ID       NUMBER(25),
    OP_TYPE         CHAR(1),
    COMMIT_TS       TIMESTAMP(3),
    REPLICAT_TS     TIMESTAMP(3),
    MAPPED_TS       TIMESTAMP(3),
    MATURITY_DATE   DATE,
    RENEWAL_DATE    DATE,
    DORMANCY_STATUS VARCHAR2(255),
    CONSTRAINT PK_FMSB_ADL_MAPPED PRIMARY KEY (RECID)
)
    TABLESPACE T24RAWOGG;

CREATE INDEX IDX_FMSB_ADL_MAPPED_OP_TYPE
    ON FMSB_ADL_MAPPED (OP_TYPE)
    TABLESPACE T24RAWOGG_IDX;

CREATE INDEX IDX_FMSB_ADL_MAPPED_WINDOW_ID
    ON FMSB_ADL_MAPPED (WINDOW_ID)
    TABLESPACE T24RAWOGG_IDX;

CREATE INDEX IDX_FMSB_ADL_MAPPED_REC_WIN_ID
    ON FMSB_ADL_MAPPED (RECID, WINDOW_ID)
    TABLESPACE T24RAWOGG_IDX;
