CREATE TABLE FMSB_AAC_MAPPED
(
    RECID          VARCHAR2(255),
    WINDOW_ID      NUMBER(25),
    COMMIT_TS      TIMESTAMP(3),
    REPLICAT_TS    TIMESTAMP(3),
    MAPPED_TS      TIMESTAMP(3),
    ID_COMP_1      VARCHAR2(255),
    ID_COMP_3      VARCHAR2(255),
    MSB_LN_PURPOSE VARCHAR2(5),
    CONSTRAINT PK_FMSB_AAC_MAPPED PRIMARY KEY (RECID)
)
    TABLESPACE T24DB_OGGDS;
