CREATE TABLE FMSB_CHG_MAPPED
(
    RECID         VARCHAR2(255),
    WINDOW_ID     NUMBER(25),
    OP_TYPE       CHAR(1),
    COMMIT_TS     TIMESTAMP(3),
    REPLICAT_TS   TIMESTAMP(3),
    MAPPED_TS     TIMESTAMP(3),
    ID_COMP_1     VARCHAR2(255),
    ID_COMP_3     VARCHAR2(255),
    CHANGE_PERIOD VARCHAR2(255),
    CHANGE_DATE   VARCHAR2(8),
    CONSTRAINT PK_FMSB_CHG_MAPPED PRIMARY KEY (RECID)
)
    TABLESPACE T24RAWOGG;

CREATE INDEX IDX_FMSB_CHG_MAPPED_OP_TYPE
    ON FMSB_CHG_MAPPED (OP_TYPE)
    TABLESPACE T24RAWOGG_IDX;
