CREATE TABLE FMSB_STM_MAPPED
(
    RECID            VARCHAR2(255),
    WINDOW_ID        NUMBER(25),
    COMMIT_TS        TIMESTAMP(3),
    REPLICAT_TS      TIMESTAMP(3),
    MAPPED_TS        TIMESTAMP(3),
    ACCOUNT_NUMBER   VARCHAR2(255),
    AMOUNT_FCY       VARCHAR2(255),
    AMOUNT_LCY       VARCHAR2(255),
    BOOKING_DATE     VARCHAR2(8),
    CRF_TYPE         VARCHAR2(255),
    CURRENCY         VARCHAR2(4),
    DATE_TIME        VARCHAR2(255),
    INPUTTER         VARCHAR2(255),
    NARRATIVE_1      VARCHAR2(255),
    NARRATIVE        VARCHAR2(1000),
    OUR_REFERENCE    VARCHAR2(255),
    PRODUCT_CATEGORY VARCHAR2(10),
    RECORD_STATUS    VARCHAR2(255),
    REVERSAL_MARKER  VARCHAR2(255),
    SYSTEM_ID        VARCHAR2(10),
    TRANS_REFERENCE  VARCHAR2(255),
    TRANSACTION_CODE VARCHAR2(10),
    VALUE_DATE       VARCHAR2(8),
    CONSTRAINT PK_FMSB_STM_MAPPED PRIMARY KEY (RECID)
)
    TABLESPACE T24DB_OGGDS;
