CREATE TABLE FMSB_ECB_MAPPED
(
    RECID           VARCHAR2(255),
    WINDOW_ID       NUMBER(25),
    OP_TYPE         CHAR(1),
    COMMIT_TS       TIMESTAMP(3),
    REPLICAT_TS     TIMESTAMP(3),
    MAPPED_TS       TIMESTAMP(3),
    CREDIT_MVMT     VARCHAR2(4000),
    CURR_ASSET_TYPE VARCHAR2(4000),
    DEBIT_MVMT      VARCHAR2(4000),
    OPEN_BALANCE    VARCHAR2(4000),
    CONSTRAINT PK_FMSB_ECB_MAPPED PRIMARY KEY (RECID)
)
    TABLESPACE T24DB_OGGDS;

CREATE INDEX IDX_FMSB_ECB_MAPPED_WINDOW_ID
    ON FMSB_ECB_MAPPED (WINDOW_ID)
    TABLESPACE T24DB_OGGDS;

CREATE INDEX IDX_FMSB_ECB_MAPPED_REC_WIN_ID
    ON FMSB_ECB_MAPPED (RECID, WINDOW_ID)
    TABLESPACE T24DB_OGGDS;
