CREATE TABLE FMSB_LMT_MAPPED
(
    RECID           VARCHAR2(255),
    WINDOW_ID       NUMBER(25),
    COMMIT_TS       TIMESTAMP(3),
    REPLICAT_TS     TIMESTAMP(3),
    MAPPED_TS       TIMESTAMP(3),
    INTERNAL_AMOUNT VARCHAR2(255),
    CONSTRAINT PK_FMSB_LMT_MAPPED PRIMARY KEY (RECID)
)
    TABLESPACE T24DB_OGGDS;

CREATE INDEX IDX_FMSB_LMT_MAPPED_REC_WIN_ID
    ON FMSB_LMT_MAPPED (RECID, WINDOW_ID)
    TABLESPACE T24DB_OGGDS;
