CREATE TABLE FMSB_TR_MAPPED
(
    RECID       VARCHAR2(255),
    WINDOW_ID   NUMBER(25),
    COMMIT_TS   TIMESTAMP(3),
    REPLICAT_TS TIMESTAMP(3),
    MAPPED_TS   TIMESTAMP(3),
    NARRATIVE_1 VARCHAR2(255),
    NARRATIVE_2 VARCHAR2(255),
    CONSTRAINT PK_FMSB_TR_MAPPED PRIMARY KEY (RECID)
)
    TABLESPACE T24DB_OGGDS;
