CREATE TABLE FMSB_AC_MAPPED
(
    RECID          VARCHAR2(255),
    WINDOW_ID      NUMBER(25),
    OP_TYPE        CHAR(1),
    COMMIT_TS      TIMESTAMP(3),
    REPLICAT_TS    TIMESTAMP(3),
    MAPPED_TS      TIMESTAMP(3),
    DEBIT_ACCOUNT  VARCHAR2(255),
    REMARKS        VARCHAR2(255),
    MSB_CHANNEL    VARCHAR2(255),
    MSB_TRANS_CODE VARCHAR2(255),
    MSB_TRANS_SEQ  VARCHAR2(255),
    CONSTRAINT PK_FMSB_AC_MAPPED PRIMARY KEY (RECID)
)
    TABLESPACE T24DB_OGGDS;

CREATE INDEX IDX_FMSB_AC_MAPPED_OP_TYPE
    ON FMSB_AC_MAPPED (OP_TYPE)
    TABLESPACE T24DB_OGGDS;
