CREATE TABLE FMSB_FX_MAPPED
(
    RECID           VARCHAR2(255),
    WINDOW_ID       NUMBER(25),
    COMMIT_TS       TIMESTAMP(3),
    REPLICAT_TS     TIMESTAMP(3),
    MAPPED_TS       TIMESTAMP(3),
    NOTES           VARCHAR2(4000),
    AMOUNT_BOUGHT   VARCHAR2(255),
    CURRENCY_BOUGHT VARCHAR2(5),
    AMOUNT_SOLD     VARCHAR2(255),
    CURRENCY_SOLD   VARCHAR2(5),
    CONSTRAINT PK_FMSB_FX_MAPPED PRIMARY KEY (RECID)
)
    TABLESPACE T24DB_OGGDS;
