CREATE TABLE FMSB_ATA_MAPPED
(
    RECID           VARCHAR2(255),
    WINDOW_ID       NUMBER(25),
    OP_TYPE         CHAR(1),
    COMMIT_TS       TIMESTAMP(3),
    REPLICAT_TS     TIMESTAMP(3),
    MAPPED_TS       TIMESTAMP(3),
    ID_COMP_1       VARCHAR2(255),
    ID_COMP_3       VARCHAR2(255),
    ACTIVITY        VARCHAR2(255),
    AMOUNT          VARCHAR2(255),
    MATURITY_DATE   DATE,
    MSB_OR_LNMAT_DT DATE,
    TERM            VARCHAR2(255),
    CONSTRAINT PK_FMSB_ATA_MAPPED PRIMARY KEY (RECID)
)
    TABLESPACE T24RAWOGG;

CREATE INDEX IDX_FMSB_ATA_MAPPED_OP_TYPE
    ON FMSB_ATA_MAPPED (OP_TYPE)
    TABLESPACE T24RAWOGG_IDX;

CREATE INDEX IDX_FMSB_ATA_MAPPED_ID_COMP_1_ID_COMP_3_ASC_ACTIVITY
    ON FMSB_ATA_MAPPED (ID_COMP_1, ID_COMP_3 ASC)
    TABLESPACE T24RAWOGG_IDX;

CREATE INDEX IDX_ATA_ID_COMP_1_ACTIVITY_AMOUNT
    ON FMSB_ATA_MAPPED (ID_COMP_1, ACTIVITY, TO_NUMBER(AMOUNT))
    TABLESPACE T24RAWOGG_IDX;
