CREATE TABLE FMSB_AIT_MAPPED
(
    RECID           VARCHAR2(255),
    WINDOW_ID       NUMBER(25),
    COMMIT_TS       TIMESTAMP(3),
    REPLICAT_TS     TIMESTAMP(3),
    MAPPED_TS       TIMESTAMP(3),
    ID_COMP_1       VARCHAR2(255),
    ID_COMP_2       VARCHAR2(255),
    ID_COMP_3       VARCHAR2(255),
    EFFECTIVE_RATE  VARCHAR2(255),
    FLOATING_INDEX  VARCHAR2(255),
    PERIODIC_PERIOD VARCHAR2(255),
    CONSTRAINT PK_FMSB_AIT_MAPPED PRIMARY KEY (RECID)
)
    TABLESPACE T24DB_OGGDS;
