CREATE TABLE FMSB_ASC_MAPPED
(
    RECID        VARCHAR2(255),
    WINDOW_ID    NUMBER(25),
    OP_TYPE      CHAR(1),
    COMMIT_TS    TIMESTAMP(3),
    REPLICAT_TS  TIMESTAMP(3),
    MAPPED_TS    TIMESTAMP(3),
    ID_COMP_1    VARCHAR2(255),
    ID_COMP_3    VARCHAR2(255),
    BILL_TYPE    VARCHAR2(2000),
    CALC_AMOUNT  VARCHAR2(2000),
    PAYMENT_FREQ VARCHAR2(2000),
    PROPERTY     VARCHAR2(2000),
    CONSTRAINT PK_FMSB_ASC_MAPPED PRIMARY KEY (RECID)
)
    TABLESPACE T24RAWOGG;

CREATE INDEX IDX_FMSB_ASC_MAPPED_OP_TYPE
    ON FMSB_ASC_MAPPED (OP_TYPE)
    TABLESPACE T24RAWOGG_IDX;

CREATE INDEX IDX_FMSB_ASC_MAPPED_ID_COMP_1_ID_COMP_3_DESC
    ON FMSB_ASC_MAPPED (ID_COMP_1, ID_COMP_3 DESC)
    TABLESPACE T24RAWOGG_IDX;

CREATE INDEX IDX_FMSB_ASC_MAPPED_WINDOW_ID
    ON FMSB_ASC_MAPPED (WINDOW_ID)
    TABLESPACE T24RAWOGG_IDX;

CREATE INDEX IDX_FMSB_ASC_MAPPED_REC_WIN_ID
    ON FMSB_ASC_MAPPED (RECID, WINDOW_ID)
    TABLESPACE T24RAWOGG_IDX;
