CREATE TABLE FMSB_ACC_MAPPED
(
    RECID            VARCHAR2(255),
    WINDOW_ID        NUMBER(25),
    COMMIT_TS        TIMESTAMP(3),
    REPLICAT_TS      TIMESTAMP(3),
    MAPPED_TS        TIMESTAMP(3),
    CATEGORY         VARCHAR2(255),
    CO_CODE          VARCHAR2(255),
    CURRENCY         VARCHAR2(4),
    CUSTOMER         VARCHAR2(255),
    FROM_DATE        VARCHAR2(2000),
    INPUTTER         VARCHAR2(1000),
    LIMIT_KEY        VARCHAR2(255),
    LOCKED_AMOUNT    VARCHAR2(2000),
    OPENING_DATE     VARCHAR2(10),
    POSTING_RESTRICT VARCHAR2(255),
    ACNAME           VARCHAR2(255),
    CONSTRAINT PK_FMSB_ACC_MAPPED PRIMARY KEY (RECID)
)
    TABLESPACE T24DB_OGGDS;

CREATE INDEX IDX_FMSB_ACC_MAPPED_WINDOW_ID
    ON FMSB_ACC_MAPPED (WINDOW_ID)
    TABLESPACE T24DB_OGGDS;

CREATE INDEX IDX_FMSB_ACC_MAPPED_REC_WIN_ID
    ON FMSB_ACC_MAPPED (RECID, WINDOW_ID)
    TABLESPACE T24DB_OGGDS;
