CREATE TABLE FMSB_STM_MAPPED
(
    RECID VARCHAR2(255), 
	WINDOW_ID NUMBER(25,0), 
	OP_TYPE VARCHAR2(10), 
	COMMIT_TS TIMESTAMP (3), 
	REPLICAT_TS TIMESTAMP (3), 
	MAPPED_TS TIMESTAMP (3), 
	ACCOUNT_NUMBER VARCHAR2(255), 
	AMOUNT_FCY NUMBER, 
	AMOUNT_LCY NUMBER, 
	BOOKING_DATE DATE, 
	CRF_TYPE VARCHAR2(255), 
	CURRENCY VARCHAR2(4), 
	DATE_TIME TIMESTAMP (6), 
	INPUTTER VARCHAR2(255), 
	NARRATIVE_1 VARCHAR2(255), 
	NARRATIVE VARCHAR2(1000), 
	OUR_REFERENCE VARCHAR2(255), 
	PRODUCT_CATEGORY NUMBER, 
	RECORD_STATUS VARCHAR2(255), 
	REVERSAL_MARKER VARCHAR2(255), 
	SYSTEM_ID VARCHAR2(10), 
	TRANS_REFERENCE VARCHAR2(255), 
	THEIR_REFERENCE VARCHAR2(255), 
	CONSOL_KEY VARCHAR2(255), 
	TRANSACTION_CODE VARCHAR2(10), 
	VALUE_DATE DATE, 
    CONSTRAINT PK_FMSB_STM_MAPPED PRIMARY KEY (RECID)
)
    TABLESPACE T24RAWOGG;

CREATE INDEX IDX_FMSB_STM_MAPPED_OP_TYPE
    ON FMSB_STM_MAPPED (OP_TYPE)
    TABLESPACE T24RAWOGG_IDX;
