BEGIN
    DBMS_SCHEDULER.create_job(
        job_name        => 'T24RAWOGG.HOURLY_PURGE_ORPHANED_DATA_JOB',
        job_type        => 'PLSQL_BLOCK',
        job_action      => q'[
            BEGIN
                DELETE FROM T24_LNMEMO_ACTIVITY_ACC_ARR_ECB         WHERE CAPTURED_TIME < SYSTIMESTAMP - INTERVAL '1' HOUR;
                DELETE FROM T24_LNMEMO_ACTIVITY_BIL                 WHERE CAPTURED_TIME < SYSTIMESTAMP - INTERVAL '1' HOUR;
                DELETE FROM T24_LNMEMO_ACTIVITY_LMT                 WHERE CAPTURED_TIME < SYSTIMESTAMP - INTERVAL '1' HOUR;
                DELETE FROM T24_LNTNEW_ACTIVITY_ACC                 WHERE CAPTURED_TIME < SYSTIMESTAMP - INTERVAL '1' HOUR;
                DELETE FROM T24_LNTNEW_ACTIVITY_ARR_AIT_ASC_AAC_ATA WHERE CAPTURED_TIME < SYSTIMESTAMP - INTERVAL '1' HOUR;
                DELETE FROM T24_CDMEMO_ACTIVITY_ACC_ARR_ECB         WHERE CAPTURED_TIME < SYSTIMESTAMP - INTERVAL '1' HOUR;
                DELETE FROM T24_CDTNEW_ACTIVITY_ACC                 WHERE CAPTURED_TIME < SYSTIMESTAMP - INTERVAL '1' HOUR;
                DELETE FROM T24_CDTNEW_ACTIVITY_ARR_AIT_ATA_CHG     WHERE CAPTURED_TIME < SYSTIMESTAMP - INTERVAL '1' HOUR;
                DELETE FROM T24_TMTRAN_STM_TRIGGER                  WHERE CAPTURED_TIME < SYSTIMESTAMP - INTERVAL '1' HOUR;
                DELETE FROM T24_DDMEMO_ACTIVITY_ACC_ARR_ECB         WHERE CAPTURED_TIME < SYSTIMESTAMP - INTERVAL '1' HOUR;
                DELETE FROM T24_DDMEMO_ACTIVITY_ADL                 WHERE CAPTURED_TIME < SYSTIMESTAMP - INTERVAL '1' HOUR;
                DELETE FROM T24_DDMEMO_ACTIVITY_LMT                 WHERE CAPTURED_TIME < SYSTIMESTAMP - INTERVAL '1' HOUR;
                DELETE FROM T24_DDTNEW_ACTIVITY_ACC                 WHERE CAPTURED_TIME < SYSTIMESTAMP - INTERVAL '1' HOUR;
                DELETE FROM T24_DDTNEW_ACTIVITY_ARR                 WHERE CAPTURED_TIME < SYSTIMESTAMP - INTERVAL '1' HOUR;
                COMMIT;
            END;
        ]',
        start_date      => SYSTIMESTAMP,
        repeat_interval => 'FREQ=HOURLY;INTERVAL=1;BYMINUTE=0;BYSECOND=0',
        enabled         => FALSE,
        auto_drop       => FALSE
    );
END;
