-- DROP JOB
BEGIN DBMS_SCHEDULER.drop_job('T24_LNMEMO_ACTIVITY_GEN_FROM_ACC_JOB', TRUE); END;
BEGIN DBMS_SCHEDULER.drop_job('T24_LNMEMO_ACTIVITY_GEN_FROM_ARR_JOB', TRUE); END;
BEGIN DBMS_SCHEDULER.drop_job('T24_LNMEMO_ACTIVITY_GEN_FROM_BIL_JOB', TRUE); END;
BEGIN DBMS_SCHEDULER.drop_job('T24_LNMEMO_ACTIVITY_GEN_FROM_ECB_JOB', TRUE); END;

-- T24_LNMEMO_ACTIVITY_GEN_FROM_ACC_JOB
BEGIN
    DBMS_SCHEDULER.create_job(
            job_name => 'T24_LNMEMO_ACTIVITY_GEN_FROM_ACC_JOB',
            job_type => 'PLSQL_BLOCK',
            job_action => q'[
            BEGIN
                EXECUTE IMMEDIATE 'ALTER SESSION SET NLS_NUMERIC_CHARACTERS = ''.,''';
                LOOP
                    T24_LNMEMO_ACTIVITY_PKG.GEN_FROM_ACC_PROC;
                END LOOP;
            END;
        ]',
            start_date => SYSTIMESTAMP,
            enabled => FALSE,
            auto_drop => FALSE
    );
END;

-- T24_LNMEMO_ACTIVITY_GEN_FROM_ARR_JOB
BEGIN
    DBMS_SCHEDULER.create_job(
            job_name => 'T24_LNMEMO_ACTIVITY_GEN_FROM_ARR_JOB',
            job_type => 'PLSQL_BLOCK',
            job_action => q'[
            BEGIN
                EXECUTE IMMEDIATE 'ALTER SESSION SET NLS_NUMERIC_CHARACTERS = ''.,''';
                LOOP
                    T24_LNMEMO_ACTIVITY_PKG.GEN_FROM_ARR_PROC;
                END LOOP;
            END;
        ]',
            start_date => SYSTIMESTAMP,
            enabled => FALSE,
            auto_drop => FALSE
    );
END;

-- T24_LNMEMO_ACTIVITY_GEN_FROM_BIL_JOB
BEGIN
    DBMS_SCHEDULER.create_job(
            job_name => 'T24_LNMEMO_ACTIVITY_GEN_FROM_BIL_JOB',
            job_type => 'PLSQL_BLOCK',
            job_action => q'[
            BEGIN
                EXECUTE IMMEDIATE 'ALTER SESSION SET NLS_NUMERIC_CHARACTERS = ''.,''';
                LOOP
                    T24_LNMEMO_ACTIVITY_PKG.GEN_FROM_BIL_PROC;
                END LOOP;
            END;
        ]',
            start_date => SYSTIMESTAMP,
            enabled => FALSE,
            auto_drop => FALSE
    );
END;

-- T24_LNMEMO_ACTIVITY_GEN_FROM_ECB_JOB
BEGIN
    DBMS_SCHEDULER.create_job(
            job_name => 'T24_LNMEMO_ACTIVITY_GEN_FROM_ECB_JOB',
            job_type => 'PLSQL_BLOCK',
            job_action => q'[
            BEGIN
                EXECUTE IMMEDIATE 'ALTER SESSION SET NLS_NUMERIC_CHARACTERS = ''.,''';
                LOOP
                    T24_LNMEMO_ACTIVITY_PKG.GEN_FROM_ECB_PROC;
                END LOOP;
            END;
        ]',
            start_date => SYSTIMESTAMP,
            enabled => FALSE,
            auto_drop => FALSE
    );
END;

-- START JOB
BEGIN DBMS_SCHEDULER.run_job('T24_LNMEMO_ACTIVITY_GEN_FROM_ACC_JOB', FALSE); END;
BEGIN DBMS_SCHEDULER.run_job('T24_LNMEMO_ACTIVITY_GEN_FROM_ARR_JOB', FALSE); END;
BEGIN DBMS_SCHEDULER.run_job('T24_LNMEMO_ACTIVITY_GEN_FROM_BIL_JOB', FALSE); END;
BEGIN DBMS_SCHEDULER.run_job('T24_LNMEMO_ACTIVITY_GEN_FROM_ECB_JOB', FALSE); END;

-- STOP JOB
BEGIN DBMS_SCHEDULER.stop_job('T24_LNMEMO_ACTIVITY_GEN_FROM_ACC_JOB', TRUE); END;
BEGIN DBMS_SCHEDULER.stop_job('T24_LNMEMO_ACTIVITY_GEN_FROM_ARR_JOB', TRUE); END;
BEGIN DBMS_SCHEDULER.stop_job('T24_LNMEMO_ACTIVITY_GEN_FROM_BIL_JOB', TRUE); END;
BEGIN DBMS_SCHEDULER.stop_job('T24_LNMEMO_ACTIVITY_GEN_FROM_ECB_JOB', TRUE); END;

-- STATUS JOB
SELECT JOB_NAME, STATE, LAST_START_DATE, NEXT_RUN_DATE, RUN_COUNT, FAILURE_COUNT
FROM DBA_SCHEDULER_JOBS
WHERE JOB_NAME LIKE 'T24_LNMEMO_ACTIVITY%';

-- ERROR JOB
SELECT JOB_NAME, STATUS, ACTUAL_START_DATE, RUN_DURATION, ERROR#, ADDITIONAL_INFO
FROM DBA_SCHEDULER_JOB_RUN_DETAILS
WHERE STATUS = 'FAILED'
AND ACTUAL_START_DATE > TO_TIMESTAMP('2025-07-14 00:00:00.000', 'YYYY-MM-DD HH24:MI:SS.FF3')
AND JOB_NAME LIKE 'T24_LNMEMO_ACTIVITY%';
ORDER BY ACTUAL_START_DATE DESC;
