-- CREATE
BEGIN
    DBMS_SCHEDULER.create_job(
        job_name         => 'T24RAWOGG.DEL_OP_TYPE_D_JOB',
        job_type         => 'PLSQL_BLOCK',
        job_action       => q'[
            BEGIN
                DELETE FROM FMSB_ARR_LNMEMO WHERE OP_TYPE = 'D';
                DELETE FROM FMSB_BIL_LNMEMO WHERE OP_TYPE = 'D';
                DELETE FROM FMSB_AIT_LNTNEW WHERE OP_TYPE = 'D';
                DELETE FROM FMSB_ARC_LNTNEW WHERE OP_TYPE = 'D';
                DELETE FROM FMSB_ARR_LNTNEW WHERE OP_TYPE = 'D';
                DELETE FROM F_DAT_MAPPED    WHERE OP_TYPE = 'D';
                DELETE FROM F_POR_MAPPED    WHERE OP_TYPE = 'D';
                DELETE FROM F_PST_MAPPED    WHERE OP_TYPE = 'D';
                DELETE FROM F_SUP_MAPPED    WHERE OP_TYPE = 'D';
                DELETE FROM F_TMV_MAPPED    WHERE OP_TYPE = 'D';
                DELETE FROM FMSB_AAC_MAPPED WHERE OP_TYPE = 'D';
                DELETE FROM FMSB_AC_MAPPED  WHERE OP_TYPE = 'D';
                DELETE FROM FMSB_ACC_MAPPED WHERE OP_TYPE = 'D';
                DELETE FROM FMSB_ADL_MAPPED WHERE OP_TYPE = 'D';
                DELETE FROM FMSB_AIT_MAPPED WHERE OP_TYPE = 'D';
                DELETE FROM FMSB_ARC_MAPPED WHERE OP_TYPE = 'D';
                DELETE FROM FMSB_ARR_MAPPED WHERE OP_TYPE = 'D';
                DELETE FROM FMSB_ASC_MAPPED WHERE OP_TYPE = 'D';
                DELETE FROM FMSB_ATA_MAPPED WHERE OP_TYPE = 'D';
                DELETE FROM FMSB_BIL_MAPPED WHERE OP_TYPE = 'D';
                DELETE FROM FMSB_BIT_MAPPED WHERE OP_TYPE = 'D';
                DELETE FROM FMSB_CAT_MAPPED WHERE OP_TYPE = 'D';
                DELETE FROM FMSB_CHG_MAPPED WHERE OP_TYPE = 'D';
                DELETE FROM FMSB_ECB_MAPPED WHERE OP_TYPE = 'D';
                DELETE FROM FMSB_FT_MAPPED  WHERE OP_TYPE = 'D';
                DELETE FROM FMSB_FX_MAPPED  WHERE OP_TYPE = 'D';
                DELETE FROM FMSB_LMT_MAPPED WHERE OP_TYPE = 'D';
                DELETE FROM FMSB_REC_MAPPED WHERE OP_TYPE = 'D';
                DELETE FROM FMSB_STM_MAPPED WHERE OP_TYPE = 'D';
                DELETE FROM FMSB_TR_MAPPED  WHERE OP_TYPE = 'D';

                COMMIT;
            END;
        ]',
        start_date       => SYSTIMESTAMP,
        repeat_interval  => 'FREQ=DAILY;BYHOUR=5;BYMINUTE=0;BYSECOND=0',
        enabled          => FALSE,
        auto_drop        => FALSE
    );
END;

-- STOP
BEGIN DBMS_SCHEDULER.stop_job('T24RAWOGG.DEL_OP_TYPE_D_JOB', FALSE); END;
BEGIN DBMS_SCHEDULER.disable('T24RAWOGG.DEL_OP_TYPE_D_JOB'); END;

-- DROP
BEGIN DBMS_SCHEDULER.drop_job('T24RAWOGG.DEL_OP_TYPE_D_JOB', TRUE); END;

-- START
BEGIN DBMS_SCHEDULER.run_job('T24RAWOGG.DEL_OP_TYPE_D_JOB', FALSE); END;
BEGIN DBMS_SCHEDULER.enable('T24RAWOGG.DEL_OP_TYPE_D_JOB'); END;

-- STATUS
SELECT JOB_NAME, STATE, LAST_START_DATE, NEXT_RUN_DATE, RUN_COUNT, FAILURE_COUNT
FROM DBA_SCHEDULER_JOBS
WHERE OWNER = 'T24RAWOGG' AND JOB_NAME = 'DEL_OP_TYPE_D_JOB';

-- ERROR
SELECT JOB_NAME, STATUS, ACTUAL_START_DATE, RUN_DURATION, ADDITIONAL_INFO
FROM DBA_SCHEDULER_JOB_RUN_DETAILS
WHERE OWNER = 'T24RAWOGG' AND JOB_NAME = 'DEL_OP_TYPE_D_JOB' AND STATUS = 'FAILED'
AND ACTUAL_START_DATE > TO_TIMESTAMP('2025-09-12 00:00:00.000', 'YYYY-MM-DD HH24:MI:SS.FF3')
ORDER BY ACTUAL_START_DATE DESC;
