
CREATE TABLE T24_TMTRAN_STM_TRIGGER
(
    JOIN_KEY VARCHAR2(100),
    WINDOW_ID NUMBER(25,0), 
	SYSTEM_ID VARCHAR2(10),
    CONSTRAINT PK_T24_TMTRAN_STM_TRIGGER PRIMARY KEY (WINDOW_ID)
)
    INMEMORY MEMCOMPRESS FOR QUERY LOW
    PRIORITY CRITICAL
    TABLESPACE T24RAWOGG;