
CREATE TABLE T24_TMTRAN_STM
(
    RECID     VARCHAR2(255),
    WINDOW_ID NUMBER(25)
)
    INMEMORY MEMCOMPRESS FOR QUERY LOW
    PRIORITY CRITICAL
    TABLESPACE T24RAWOGG;

CREATE INDEX IDX_T24_TMTRAN_STM_REC_WIN_ID
    ON T24_TMTRAN_STM (RECID, WINDOW_ID)
    TABLESPACE T24RAWOGG;
