CREATE GLOBAL TEMPORARY TABLE TMP_T24_TMTRAN_STM_TRIGGER
(   
    WINDOW_ID NUMBER(25)
) ON COMMIT DELETE ROWS;


CREATE INDEX IDX_TMP_T24_TMTRAN_STM_TRIGGER
    ON TMP_T24_TMTRAN_STM_TRIGGER (WINDOW_ID);