CREATE MATERIALIZED VIEW LOG ON FMSB_ASC_MAPPED
TABLESPACE T24RAWOGG
WITH ROWID, SEQUENCE (ID_COMP_1, ID_COMP_3)
INCLUDING NEW VALUES;

CREATE MATERIALIZED VIEW MV_FMSB_ASC_LNTNEW
TABLESPACE T24RAWOGG
NOLOGGING
CACHE
BUILD IMMEDIATE
REFRESH FAST ON COMMIT
AS
SELECT 
    ID_COMP_1,
    MAX(ID_COMP_3) AS MAX_ID_COMP_3
FROM 
    FMSB_ASC_MAPPED
GROUP BY 
    ID_COMP_1;

CREATE UNIQUE INDEX IDX_MV_ASC_LNTNEW_ID_COMP_1 
ON MV_FMSB_ASC_LNTNEW (ID_COMP_1)
TABLESPACE T24RAWOGG;