CREATE MATERIALIZED VIEW LOG ON FMSB_ATA_MAPPED
TABLESPACE T24DB_OGGDS
WITH ROWID, SEQUENCE (ID_COMP_1, ID_COMP_3, ACTIVITY, AMOUNT)
INCLUDING NEW VALUES;

CREATE MATERIALIZED VIEW MV_FMSB_ATA_LNTNEW
TABLESPACE T24DB_OGGDS
NOLOGGING
CACHE
BUILD IMMEDIATE
REFRESH FAST ON COMMIT
AS
SELECT 
    ID_COMP_1,
    MAX(ID_COMP_3) AS MAX_ID_COMP_3,
    MIN(ID_COMP_3) AS MIN_ID_COMP_3,
    MAX(
        CASE
            WHEN ACTIVITY IN ('LENDING-NEW-ARRANGEMENT','LENDING-TAKEOVER-ARRANGEMENT')
                THEN AMOUNT
            ELSE '0'
        END) AS ORGAMT
FROM 
    FMSB_ATA_MAPPED
GROUP BY 
    ID_COMP_1;

CREATE UNIQUE INDEX IDX_MV_FMSB_ATA_LNTNEW_ID_COMP_1 
ON MV_FMSB_ATA_LNTNEW (ID_COMP_1)
TABLESPACE T24DB_OGGDS;