CREATE OR REPLACE VIEW VW_FMSB_ATA_LNTNEW AS
SELECT ID_COMP_1,
       MIN(ID_COMP_3)   AS MIN_ID_COMP_3,
       MAX(
               CASE
                   WHEN ACTIVITY IN ('LENDING-NEW-ARRANGEMENT', 'LENDING-TAKEOVER-ARRANGEMENT')
                       THEN AMOUNT
                   ELSE '0'
                   END) AS ORGAMT
FROM FMSB_ATA_MAPPED
GROUP BY ID_COMP_1;