ALTER SESSION SET NLS_NUMERIC_CHARACTERS = '.,';

BEGIN
    T24_CDTNEW_ACTIVITY_PKG.GEN_FROM_ACC_PROC;
END;

SELECT
    ACCTNO,
    TO_CHAR(COMMIT_TS, 'YYYY-MM-DD HH24:MI:SS.FF3') AS COMMIT_TS,
    TO_CHAR(REPLICAT_TS, 'YYYY-MM-DD HH24:MI:SS.FF3') AS REPLICAT_TS,
    TO_CHAR(MAPPED_TS, 'YYYY-MM-DD HH24:MI:SS.FF3') AS MAPPED_TS,
    TO_CHAR(CHANGED_TIME, 'YYYY-MM-DD HH24:MI:SS.FF3') AS CHANGED_TIME,
    EXTRACT(SECOND FROM (CHANGED_TIME - REPLICAT_TS)) AS LATENCY,
    CALL_CDC
FROM T24_CDTNEW_ACTIVITY
WHERE CHANGED_TIME
    > TO_TIMESTAMP('2025-09-10 00:00:00.000', 'YYYY-MM-DD HH24:MI:SS.FF3')
--    BETWEEN TO_TIMESTAMP('2025-07-13 00:14:00.000', 'YYYY-MM-DD HH24:MI:SS.FF3') AND TO_TIMESTAMP('2025-09-10 00:26:00.000', 'YYYY-MM-DD HH24:MI:SS.FF3')
--    AND EXTRACT(SECOND FROM (CHANGED_TIME - REPLICAT_TS)) > 1
ORDER BY CHANGED_TIME DESC
--ORDER BY LATENCY DESC
FETCH FIRST 10 ROWS ONLY;

SELECT
    COUNT(*) AS TOTAL_RECORDS,
    PERCENTILE_CONT(0.10) WITHIN GROUP (ORDER BY LATENCY) AS P10_LATENCY,
    PERCENTILE_CONT(0.25) WITHIN GROUP (ORDER BY LATENCY) AS P25_LATENCY,
    PERCENTILE_CONT(0.50) WITHIN GROUP (ORDER BY LATENCY) AS P50_LATENCY,
    PERCENTILE_CONT(0.75) WITHIN GROUP (ORDER BY LATENCY) AS P75_LATENCY,
    PERCENTILE_CONT(0.90) WITHIN GROUP (ORDER BY LATENCY) AS P90_LATENCY,
    MAX(LATENCY) AS MAX_LATENCY
FROM (
    SELECT EXTRACT(SECOND FROM (CHANGED_TIME - REPLICAT_TS)) AS LATENCY
    FROM T24_CDTNEW_ACTIVITY
    WHERE CHANGED_TIME
    > TO_TIMESTAMP('2025-09-10 00:00:00.000', 'YYYY-MM-DD HH24:MI:SS.FF3')
--    BETWEEN TO_TIMESTAMP('2025-09-10 00:14:00.000', 'YYYY-MM-DD HH24:MI:SS.FF3') AND TO_TIMESTAMP('2025-09-10 00:26:00.000', 'YYYY-MM-DD HH24:MI:SS.FF3')
--    AND EXTRACT(SECOND FROM (CHANGED_TIME - REPLICAT_TS)) > 2
);

SELECT * FROM T24_CDTNEW_ACTIVITY
--WHERE ACCTNO = 30000000793
ORDER BY CHANGED_TIME DESC
FETCH FIRST 10 ROWS ONLY;

SELECT 'F_DAT_MAPPED', COUNT(*) FROM F_DAT_MAPPED
UNION ALL
SELECT 'FMSB_ACC_MAPPED', COUNT(*) FROM FMSB_ACC_MAPPED
UNION ALL
SELECT 'FMSB_ARR_CD', COUNT(*) FROM FMSB_ARR_CD
UNION ALL
SELECT 'FMSB_ATA_MAPPED', COUNT(*) FROM FMSB_ATA_MAPPED
UNION ALL
SELECT 'FMSB_AIT_CDTNEW', COUNT(*) FROM FMSB_AIT_CDTNEW
UNION ALL
SELECT 'FMSB_ADL_MAPPED', COUNT(*) FROM FMSB_ADL_MAPPED
UNION ALL
SELECT 'FMSB_CHG_MAPPED', COUNT(*) FROM FMSB_CHG_MAPPED
UNION ALL
SELECT 'T24_CDTNEW_ACTIVITY_ARR', COUNT(*) FROM T24_CDTNEW_ACTIVITY_ARR
UNION ALL
SELECT 'T24_CDTNEW_ACTIVITY_ACC', COUNT(*) FROM T24_CDTNEW_ACTIVITY_ACC
UNION ALL
SELECT 'T24_CDTNEW_ACTIVITY_ATA', COUNT(*) FROM T24_CDTNEW_ACTIVITY_ATA
UNION ALL
SELECT 'T24_CDTNEW_ACTIVITY', COUNT(*) FROM T24_CDTNEW_ACTIVITY;
