CREATE TABLE T24_CDMEMO_ACTIVITY 
(	
    SEQUENCE_NO  NUMBER(18, 0) GENERATED ALWAYS AS IDENTITY,
    ACCTNO       NUMBER(19, 0), 
	CURTYP       VARCHAR2(4), 
	CDNUM        NUMBER(19, 0), 
	CBAL         NUMBER(15, 2), 
	HOLD         NUMBER(15, 2), 
	STATUS       NUMBER(1, 0), 
	ACCINT       NUMBER(17, 5), 
	WDRWH        NUMBER(13, 2), 
	PENAMT       NUMBER(13, 2), 
	WINDOW_ID    NUMBER(25, 0), 
	COMMIT_TS    TIMESTAMP (3), 
	REPLICAT_TS  TIMESTAMP (3), 
	MAPPED_TS    TIMESTAMP (3), 
	CHANGED_TIME TIMESTAMP (3) DEFAULT SYSTIMESTAMP, 
	CALL_CDC     VARCHAR2(3),
    CONSTRAINT PK_T24_CDMEMO_ACTIVITY PRIMARY KEY (SEQUENCE_NO)
)
    TABLESPACE T24RAWOGG
    PARTITION BY RANGE (CHANGED_TIME)
    INTERVAL (NUMTODSINTERVAL(1, 'DAY'))
(
    PARTITION P1 VALUES LESS THAN (TIMESTAMP '2024-01-01 00:00:00')
        LOGGING
        NOCOMPRESS
        TABLESPACE T24RAWOGG
        PCTFREE 10
        INITRANS 5
        MAXTRANS 255
        STORAGE (
        INITIAL 1024M
        NEXT 1M
        MINEXTENTS 1
        MAXEXTENTS UNLIMITED
        BUFFER_POOL DEFAULT
        )
)
    NOCACHE
    MONITORING;
