CREATE TABLE T24_CDMEMO_ACTIVITY (
    ACCTNO         NUMBER(19,0),
    CURTYP         VARCHAR2(4),
    CDNUM          NUMBER(19,0),
    CBAL           NUMBER(15,2),
    HOLD           NUMBER(15,2),
    STATUS         NUMBER(1,0),
    ACCINT         NUMBER(17,5),
    WDRWH          NUMBER(13,2),
    PENAMT         NUMBER(13,2),
    WINDOW_ID      NUMBER(25, 0),
    COMMIT_TS      TIMESTAMP(3),
    REPLICAT_TS    TIMESTAMP(3),
    MAPPED_TS      TIMESTAMP(3),
    CHANGED_TIME   TIMESTAMP(3) DEFAULT SYSTIMESTAMP,
    CALL_CDC       VARCHAR2(3)
)
    TABLESPACE T24RAWOGG;
