CREATE TABLE T24_CDTNEW_ACTIVITY (
    BANKNO         NUMBER(2,0),
    ACCTNO         NUMBER(19,0),
    ACTYPE         VARCHAR2(1),
    ACNAME         VARCHAR2(40),
    CIFNO          NUMBER(19,0),
    TYPE           VARCHAR2(10),
    BRN            NUMBER(5,0),
    STATUS         NUMBER(1,0),
    CDNUM          NUMBER(19,0),
    ORGBAL         NUMBER(15,2),
    CBAL           NUMBER(15,2),
    HOLD           NUMBER(15,2),
    ACCINT         NUMBER(17,5),
    WDRWH          NUMBER(13,2),
    RNWCTR         NUMBER(3,0),
    PENAMT         NUMBER(13,2),
    ISSDT          NUMBER(7,0),
    MATDT          NUMBER(7,0),
    CDTERM         NUMBER(5,0),
    CDTCOD         VARCHAR2(1),
    RENEW          VARCHAR2(1),
    DACTN          NUMBER(19,0),
    RATE           NUMBER(11,9),
    CURTYP         VARCHAR2(4),
    CDMUID         VARCHAR2(10),
    RS2DT7         NUMBER(7,0),
    WINDOW_ID      NUMBER(25, 0),
    COMMIT_TS      TIMESTAMP(3),
    REPLICAT_TS    TIMESTAMP(3),
    MAPPED_TS      TIMESTAMP(3),
    CHANGED_TIME   TIMESTAMP(3) DEFAULT SYSTIMESTAMP,
    CALL_CDC       VARCHAR2(3)
)
    TABLESPACE T24RAWOGG;