CREATE TABLE T24_LNMEMO_ACTIVITY
(
    ACCTNO       NUMBER(19, 0),
    CURTYP       VARCHAR2(4),
    CBAL         NUMBER(15, 2),
    HOLD         NUMBER(15, 2),
    DRLIMT       NUMBER(18, 2), --NUMBER(15, 2) 
    ACCINT       NUMBER(17, 5),
    COMACC       NUMBER(15, 5),
    OTHCHG       NUMBER(13, 2),
    BILPRN       NUMBER(15, 2),
    BILINT       NUMBER(13, 2),
    BILESC       NUMBER(13, 2),
    BILLC        NUMBER(13, 2),
    BILOC        NUMBER(13, 2),
    BILMC        NUMBER(13, 2),
    WINDOW_ID    NUMBER(25, 0),
    COMMIT_TS    TIMESTAMP(3),
    REPLICAT_TS  TIMESTAMP(3),
    MAPPED_TS    TIMESTAMP(3),
    CHANGED_TIME TIMESTAMP(3) DEFAULT SYSTIMESTAMP,
    CALL_CDC     VARCHAR2(3)
)
    TABLESPACE T24DB_OGGDS;
