CREATE TABLE T24_DDTNEW_ACTIVITY 
(	
    BRANCH       VARCHAR2(9), 
	ACCTNO       NUMBER(19,0), 
	ACNAME       VARCHAR2(150), 
	CIFNO        NUMBER(19,0), 
	STATUS       NUMBER(1,0), 
	SCCODE       VARCHAR2(30), 
	DLA7         NUMBER(7,0), 
	DLA6         NUMBER(6,0), 
	ACTYPE       CHAR(1), 
	DDCTYP       VARCHAR2(4), 
	HOLD         NUMBER(15,2), 
	CBAL         NUMBER(15,2), 
	ODLIMT       NUMBER(15,2), 
	RATE         NUMBER(11,9), 
	DATOP7       NUMBER(7,0), 
	ACCRUE       NUMBER(15,5), 
	WINDOW_ID    NUMBER(25,0), 
	COMMIT_TS    TIMESTAMP (3), 
	REPLICAT_TS  TIMESTAMP (3), 
	MAPPED_TS    TIMESTAMP (3), 
	CHANGED_TIME TIMESTAMP (3) DEFAULT SYSTIMESTAMP, 
	CALL_CDC     VARCHAR2(3)
)
    TABLESPACE T24RAWOGG;