CREATE TABLE T24_DDMEMO_ACTIVITY (
    BRANCH        VARCHAR2(9),
    ACCTNO        NUMBER(19,0),
    ACNAME        VARCHAR2(40),
    CIFNO         NUMBER(19,0),
    STATUS        NUMBER(1,0),
    SCCODE        VARCHAR2(10),
    DLA7          NUMBER(7,0),
    DLA6          NUMBER(6,0),
    HOLD          NUMBER(15,2),
    CBAL          NUMBER(15,2),
    ACCRUE        NUMBER(15,5),
    ODLIMT        NUMBER(15,2),
    WINDOW_ID      NUMBER(25, 0),
    COMMIT_TS     TIMESTAMP(3),
    REPLICAT_TS   TIMESTAMP(3),
    MAPPED_TS     TIMESTAMP(3),
    CHANGED_TIME  TIMESTAMP(3) DEFAULT SYSTIMESTAMP,
    CALL_CDC      VARCHAR2(3)
)
    TABLESPACE T24RAWOGG;