CREATE TABLE T24_DDTNEW_ACTIVITY 
(
    SEQUENCE_NO  NUMBER(18, 0) GENERATED ALWAYS AS IDENTITY,	
    BRANCH       VARCHAR2(9), 
	ACCTNO       NUMBER(19,0), 
	ACNAME       VARCHAR2(150), 
	CIFNO        NUMBER(19,0), 
	STATUS       NUMBER(1,0), 
	SCCODE       VARCHAR2(30), 
	DLA7         NUMBER(7,0), 
	DLA6         NUMBER(6,0), 
	ACTYPE       CHAR(1), 
	DDCTYP       VARCHAR2(4), 
	HOLD         NUMBER(15,2), 
	CBAL         NUMBER(15,2), 
	ODLIMT       NUMBER(15,2), 
	RATE         NUMBER(11,9), 
	DATOP7       NUMBER(7,0), 
	ACCRUE       NUMBER(15,5), 
	WINDOW_ID    NUMBER(25,0), 
	COMMIT_TS    TIMESTAMP (3), 
	REPLICAT_TS  TIMESTAMP (3), 
	MAPPED_TS    TIMESTAMP (3), 
	CHANGED_TIME TIMESTAMP (3) DEFAULT SYSTIMESTAMP NOT NULL, 
	CALL_CDC     VARCHAR2(3),
    CONSTRAINT PK_T24_DDTNEW_ACTIVITY PRIMARY KEY (SEQUENCE_NO)
)
    TABLESPACE T24RAWOGG
    PARTITION BY RANGE (CHANGED_TIME)
    INTERVAL (NUMTODSINTERVAL(1, 'DAY'))
(
    PARTITION P1 VALUES LESS THAN (TIMESTAMP '2024-01-01 00:00:00')
        LOGGING
        NOCOMPRESS
        TABLESPACE T24RAWOGG
        PCTFREE 10
        INITRANS 5
        MAXTRANS 255
        STORAGE (
        INITIAL 1024M
        NEXT 1M
        MINEXTENTS 1
        MAXEXTENTS UNLIMITED
        BUFFER_POOL DEFAULT
        )
)
    NOCACHE
    MONITORING;

CREATE INDEX IDX_T24_DDTNEW_ACTIVITY_CT_SN
    ON T24RAWOGG.T24_DDTNEW_ACTIVITY (CHANGED_TIME, SEQUENCE_NO)
    LOCAL TABLESPACE T24RAWOGG_IDX;