CREATE TABLE T24_LNTNEW_ACTIVITY
(
    SEQUENCE_NO  NUMBER(18, 0) GENERATED ALWAYS AS IDENTITY,
    BRN          CHAR(9),
    ACCTNO       NUMBER(19, 0),
    LNNUM        NUMBER(19, 0),
    CIFNO        NUMBER(19, 0),
    ACNAME       VARCHAR2(150),
    STATUS       NUMBER(1, 0),
    TYPE         VARCHAR2(30),
    CURTYP       VARCHAR2(4),
    ORGAMT       NUMBER(15, 2),
    DRLIMT       NUMBER(15, 2),
    HOLD         NUMBER(15, 2),
    CBAL         NUMBER(15, 2),
    OTHCHG       NUMBER(13, 2),
    ACCINT       NUMBER(17, 5),
    COMACC       NUMBER(15, 5),
    PMTAMT       NUMBER(15, 2),
    FNLPMT       NUMBER(15, 2),
    BILPRN       NUMBER(15, 2),
    BILINT       NUMBER(13, 2),
    BILESC       NUMBER(13, 2),
    BILLC        NUMBER(13, 2),
    BILOC        NUMBER(13, 2),
    BILMC        NUMBER(13, 2),
    BILLCO       NUMBER(13, 2),
    YSOBAL       NUMBER(15, 2),
    DATOPN       NUMBER(7, 0),
    FRELDT       NUMBER(7, 0),
    FULLDT       NUMBER(7, 0),
    MATDT        NUMBER(7, 0),
    RATE         NUMBER(11, 9),
    LCTYPE       NUMBER(3, 0),
    ACCMLC       CHAR(1),
    TERM         NUMBER(5, 0),
    TMCODE       CHAR(1),
    FREQ         NUMBER(3, 0),
    IPFREQ       NUMBER(3, 0),
    ODIND        CHAR(1),
    PURCOD       VARCHAR2(2),
    WINDOW_ID    NUMBER(25, 0),
    COMMIT_TS    TIMESTAMP(3),
    REPLICAT_TS  TIMESTAMP(3),
    MAPPED_TS    TIMESTAMP(3),
    CHANGED_TIME TIMESTAMP(3) DEFAULT SYSTIMESTAMP NOT NULL,
    CALL_CDC     VARCHAR2(3),
    CONSTRAINT PK_T24_LNTNEW_ACTIVITY PRIMARY KEY (SEQUENCE_NO)
)
    TABLESPACE T24RAWOGG
    PARTITION BY RANGE (CHANGED_TIME)
    INTERVAL (NUMTODSINTERVAL(1, 'DAY'))
(
    PARTITION P1 VALUES LESS THAN (TIMESTAMP '2024-01-01 00:00:00')
        LOGGING
        NOCOMPRESS
        TABLESPACE T24RAWOGG
        PCTFREE 10
        INITRANS 5
        MAXTRANS 255
        STORAGE (
        INITIAL 1024M
        NEXT 1M
        MINEXTENTS 1
        MAXEXTENTS UNLIMITED
        BUFFER_POOL DEFAULT
        )
)
    NOCACHE
    MONITORING;

CREATE INDEX IDX_T24_LNTNEW_ACTIVITY_CT_SN
    ON T24RAWOGG.T24_LNTNEW_ACTIVITY (CHANGED_TIME, SEQUENCE_NO)
    LOCAL TABLESPACE T24RAWOGG_IDX;
