CREATE TABLE T24_CDTNEW_ACTIVITY 
(
    SEQUENCE_NO  NUMBER(18, 0) GENERATED ALWAYS AS IDENTITY,
	BANKNO       NUMBER(2, 0), 
	ACCTNO       NUMBER(19, 0), 
	ACTYPE       CHAR(1), 
	ACNAME       VARCHAR2(150), 
	CIFNO        NUMBER(19, 0), 
	STATUS       NUMBER(1, 0), 
	BRN          VARCHAR2(9), 
	CDNUM        NUMBER(19, 0), 
	ORGBAL       NUMBER(15, 2), 
	CBAL         NUMBER(15, 2), 
	HOLD         NUMBER(15, 2), 
	ACCINT       NUMBER(17, 5), 
	WDRWH        NUMBER(13, 2), 
	RNWCTR       NUMBER(3, 0), 
	ISSDT        NUMBER(7, 0), 
	MATDT        NUMBER(7, 0), 
	CDTERM       NUMBER(5, 0), 
	RENEW        CHAR(1), 
	DACTN        NUMBER(19, 0), 
	RATE         NUMBER(11, 9), 
	CURTYP       VARCHAR2(4), 
	CDMUID       VARCHAR2(30), 
	PENAMT       NUMBER(13, 2), 
	TYPE         VARCHAR2(40), 
	CDTCOD       CHAR(1), 
	RS2DT7       NUMBER(7, 0), 
	WINDOW_ID    NUMBER(25, 0), 
	COMMIT_TS    TIMESTAMP (3), 
	REPLICAT_TS  TIMESTAMP (3), 
	MAPPED_TS    TIMESTAMP (3), 
	CHANGED_TIME TIMESTAMP (3) DEFAULT SYSTIMESTAMP NOT NULL, 
	CALL_CDC     VARCHAR2(3),
    CONSTRAINT PK_T24_CDTNEW_ACTIVITY PRIMARY KEY (SEQUENCE_NO)
)
    TABLESPACE T24RAWOGG
    PARTITION BY RANGE (CHANGED_TIME)
    INTERVAL (NUMTODSINTERVAL(1, 'DAY'))
(
    PARTITION P1 VALUES LESS THAN (TIMESTAMP '2024-01-01 00:00:00')
        LOGGING
        NOCOMPRESS
        TABLESPACE T24RAWOGG
        PCTFREE 10
        INITRANS 5
        MAXTRANS 255
        STORAGE (
        INITIAL 1024M
        NEXT 1M
        MINEXTENTS 1
        MAXEXTENTS UNLIMITED
        BUFFER_POOL DEFAULT
        )
)
    NOCACHE
    MONITORING;
	
CREATE INDEX IDX_T24_CDTNEW_ACTIVITY_CT_SN
    ON T24RAWOGG.T24_CDTNEW_ACTIVITY (CHANGED_TIME, SEQUENCE_NO)
    LOCAL TABLESPACE T24RAWOGG_IDX;