CREATE TABLE T24_TMTRAN 
   (	SEQUENCE_NO  NUMBER(18, 0) GENERATED ALWAYS AS IDENTITY, 
	TMTXSTAT VARCHAR2(2), 
	TMOFFSET VARCHAR2(100), 
	TMIBTTRN CHAR(1), 
	TMEQVTRN CHAR(1), 
	TMSUMTRN VARCHAR2(15), 
	TMTELLID VARCHAR2(100), 
	TMTXSEQ VARCHAR2(100), 
	TMTXCD VARCHAR2(30), 
	TMENTDT7 NUMBER(8,0), 
	TMEFFDT7 NUMBER(8,0), 
	TMAPPTYPE CHAR(1), 
	TMHOSTTXCD NUMBER(5,0), 
	TMTIMENT NUMBER(6,0), 
	TMORGAMT NUMBER(20,2), 
	TMTXAMT NUMBER(20,2), 
	TMGLCUR VARCHAR2(4), 
	TMACCTNO VARCHAR2(30), 
	TMDORC CHAR(1), 
	TMSSEQ VARCHAR2(30), 
	TMEFTH VARCHAR2(1000), 
	TMRESV07 VARCHAR2(60), 
	TMTKTN VARCHAR2(150), 
	WINDOW_ID NUMBER(25,0), 
	COMMIT_TS TIMESTAMP (3), 
	REPLICAT_TS TIMESTAMP (3), 
	MAPPED_TS TIMESTAMP (3), 
    CHANGED_TIME TIMESTAMP(3) DEFAULT SYSTIMESTAMP,
	CALL_CDC VARCHAR2(3), 
	 CONSTRAINT PK_T24_TMTRAN PRIMARY KEY (SEQUENCE_NO)
   ) 
   TABLESPACE T24RAWOGG
    PARTITION BY RANGE (CHANGED_TIME)
    INTERVAL (NUMTODSINTERVAL(1, 'DAY'))
    (
    PARTITION P1 VALUES LESS THAN (TIMESTAMP '2024-01-01 00:00:00')
        LOGGING
        NOCOMPRESS
        TABLESPACE T24RAWOGG
        PCTFREE 10
        INITRANS 5
        MAXTRANS 255
        STORAGE (
        INITIAL 1024M
        NEXT 1M
        MINEXTENTS 1
        MAXEXTENTS UNLIMITED
        BUFFER_POOL DEFAULT
        )
)
    NOCACHE
    MONITORING;