SELECT 'F_DATES_MAPPED' AS NAME, 'DAT' AS ALIAS, COUNT(*) AS COUNT FROM F_DAT_MAPPED
UNION ALL
SELECT 'F_POSTING_RESTRICT_MAPPED', 'PST', COUNT(*) FROM F_PST_MAPPED
UNION ALL
SELECT 'FMSB_LIMIT_MAPPED', 'LMT', COUNT(*) FROM FMSB_LMT_MAPPED
UNION ALL
SELECT 'FMSB_EB_CONTRACT_BALANCES_MAPPED', 'ECB', COUNT(*) FROM FMSB_ECB_MAPPED
UNION ALL
SELECT 'FMSB_AA_ARRANGEMENT_ACTIVITY_MAPPED', 'ARC', COUNT(*) FROM FMSB_ARC_MAPPED
UNION ALL
SELECT 'FMSB_AA_ARRANGEMENT_MAPPED', 'ARR', COUNT(*) FROM FMSB_ARR_MAPPED
UNION ALL
SELECT 'FMSB_ACCOUNT_MAPPED', 'ACC', COUNT(*) FROM FMSB_ACC_MAPPED
UNION ALL
SELECT 'FMSB_AC_CHARGE_REQUEST_MAPPED', 'AC', COUNT(*) FROM FMSB_AC_MAPPED
UNION ALL
SELECT 'F_POR_SUPPLEMENTARY000_MAPPED', 'SUP', COUNT(*) FROM F_SUP_MAPPED
UNION ALL
SELECT 'F_EB_MSBH_TM_CLEARING_DATA_VN_MAPPED', 'TMV', COUNT(*) FROM F_TMV_MAPPED
UNION ALL
SELECT 'FMSB_FOREX_MAPPED', 'FX', COUNT(*) FROM FMSB_FX_MAPPED
UNION ALL
SELECT 'F_POR_TRANSACTION_MAPPED', 'POR', COUNT(*) FROM F_POR_MAPPED
UNION ALL
SELECT 'FMSB_AA_ACCOUNT_DETAILS_MAPPED', 'ADL', COUNT(*) FROM FMSB_ADL_MAPPED
UNION ALL
SELECT 'FMSB_AA_ARR_ACCOUNT_MAPPED', 'AAC', COUNT(*) FROM FMSB_AAC_MAPPED
UNION ALL
SELECT 'FMSB_AA_ARR_CHANGE_PRODUCT_MAPPED', 'CHG', COUNT(*) FROM FMSB_CHG_MAPPED
UNION ALL
SELECT 'FMAB_AA_ARR_INTERSET_MAPPED', 'AIT', COUNT(*) FROM FMSB_AIT_MAPPED
UNION ALL
SELECT 'FMSB_AA_ARR_PAYMENT_SCHEDULE_MAPPED', 'ASC', COUNT(*) FROM FMSB_ASC_MAPPED
UNION ALL
SELECT 'FMSB_AA_ARR_TERM_AMOUNT_MAPPED', 'ATA', COUNT(*) FROM FMSB_ATA_MAPPED
UNION ALL
SELECT 'FMSB_AA_BILL_DETAILS_MAPPED', 'BIL', COUNT(*) FROM FMSB_BIL_MAPPED
UNION ALL
SELECT 'FMSB_BASIC_INTEREST_MAPPED', 'BIT', COUNT(*) FROM FMSB_BIT_MAPPED
UNION ALL
SELECT 'FMSB_CATEG_ENTRY_MAPPED', 'CAT', COUNT(*) FROM FMSB_CAT_MAPPED
UNION ALL
SELECT 'FMSB_FUNDS_TRANSFER_MAPPED', 'FT', COUNT(*) FROM FMSB_FT_MAPPED
UNION ALL
SELECT 'FMSB_RE_CONSOL_SPEC_ENTRY_MAPPED', 'REC', COUNT(*) FROM FMSB_REC_MAPPED
UNION ALL
SELECT 'FMSB_STMT_ENTRY_MAPPED', 'STM', COUNT(*) FROM FMSB_STM_MAPPED
UNION ALL
SELECT 'FMSB_TRANSACTION_MAPPED', 'TR', COUNT(*) FROM FMSB_TR_MAPPED;
