-- DAILY_PURGE_OP_TYPE_D_JOB
BEGIN DBMS_SCHEDULER.drop_job('T24RAWOGG.DAILY_PURGE_OP_TYPE_D_JOB', FALSE); END;

BEGIN DBMS_SCHEDULER.stop_job('T24RAWOGG.DAILY_PURGE_OP_TYPE_D_JOB', FALSE); END;
BEGIN DBMS_SCHEDULER.run_job('T24RAWOGG.DAILY_PURGE_OP_TYPE_D_JOB', FALSE); END;

BEGIN DBMS_SCHEDULER.disable('T24RAWOGG.DAILY_PURGE_OP_TYPE_D_JOB'); END;
BEGIN DBMS_SCHEDULER.enable('T24RAWOGG.DAILY_PURGE_OP_TYPE_D_JOB'); END;

-- T24_LNMEMO_ACTIVITY_JOB
BEGIN DBMS_SCHEDULER.drop_job('T24RAWOGG.T24_LNMEMO_ACTIVITY_GEN_FROM_ACC_JOB', FALSE); END;
BEGIN DBMS_SCHEDULER.drop_job('T24RAWOGG.T24_LNMEMO_ACTIVITY_GEN_FROM_ARR_JOB', FALSE); END;
BEGIN DBMS_SCHEDULER.drop_job('T24RAWOGG.T24_LNMEMO_ACTIVITY_GEN_FROM_BIL_JOB', FALSE); END;
BEGIN DBMS_SCHEDULER.drop_job('T24RAWOGG.T24_LNMEMO_ACTIVITY_GEN_FROM_ECB_JOB', FALSE); END;

BEGIN DBMS_SCHEDULER.stop_job('T24RAWOGG.T24_LNMEMO_ACTIVITY_GEN_FROM_ACC_JOB', FALSE); END;
BEGIN DBMS_SCHEDULER.stop_job('T24RAWOGG.T24_LNMEMO_ACTIVITY_GEN_FROM_ARR_JOB', FALSE); END;
BEGIN DBMS_SCHEDULER.stop_job('T24RAWOGG.T24_LNMEMO_ACTIVITY_GEN_FROM_BIL_JOB', FALSE); END;
BEGIN DBMS_SCHEDULER.stop_job('T24RAWOGG.T24_LNMEMO_ACTIVITY_GEN_FROM_ECB_JOB', FALSE); END;

BEGIN DBMS_SCHEDULER.run_job('T24RAWOGG.T24_LNMEMO_ACTIVITY_GEN_FROM_ACC_JOB', FALSE); END;
BEGIN DBMS_SCHEDULER.run_job('T24RAWOGG.T24_LNMEMO_ACTIVITY_GEN_FROM_ARR_JOB', FALSE); END;
BEGIN DBMS_SCHEDULER.run_job('T24RAWOGG.T24_LNMEMO_ACTIVITY_GEN_FROM_BIL_JOB', FALSE); END;
BEGIN DBMS_SCHEDULER.run_job('T24RAWOGG.T24_LNMEMO_ACTIVITY_GEN_FROM_ECB_JOB', FALSE); END;

-- T24_LNTNEW_ACTIVITY_JOB
BEGIN DBMS_SCHEDULER.drop_job('T24RAWOGG.T24_LNTNEW_ACTIVITY_GEN_FROM_ACC_JOB', FALSE); END;
BEGIN DBMS_SCHEDULER.drop_job('T24RAWOGG.T24_LNTNEW_ACTIVITY_GEN_FROM_ARR_JOB', FALSE); END;
BEGIN DBMS_SCHEDULER.drop_job('T24RAWOGG.T24_LNTNEW_ACTIVITY_GEN_FROM_AIT_JOB', FALSE); END;
BEGIN DBMS_SCHEDULER.drop_job('T24RAWOGG.T24_LNTNEW_ACTIVITY_GEN_FROM_ASC_JOB', FALSE); END;

BEGIN DBMS_SCHEDULER.stop_job('T24RAWOGG.T24_LNTNEW_ACTIVITY_GEN_FROM_ACC_JOB', FALSE); END;
BEGIN DBMS_SCHEDULER.stop_job('T24RAWOGG.T24_LNTNEW_ACTIVITY_GEN_FROM_ARR_JOB', FALSE); END;
BEGIN DBMS_SCHEDULER.stop_job('T24RAWOGG.T24_LNTNEW_ACTIVITY_GEN_FROM_AIT_JOB', FALSE); END;
BEGIN DBMS_SCHEDULER.stop_job('T24RAWOGG.T24_LNTNEW_ACTIVITY_GEN_FROM_ASC_JOB', FALSE); END;

BEGIN DBMS_SCHEDULER.run_job('T24RAWOGG.T24_LNTNEW_ACTIVITY_GEN_FROM_ACC_JOB', FALSE); END;
BEGIN DBMS_SCHEDULER.run_job('T24RAWOGG.T24_LNTNEW_ACTIVITY_GEN_FROM_ARR_JOB', FALSE); END;
BEGIN DBMS_SCHEDULER.run_job('T24RAWOGG.T24_LNTNEW_ACTIVITY_GEN_FROM_AIT_JOB', FALSE); END;
BEGIN DBMS_SCHEDULER.run_job('T24RAWOGG.T24_LNTNEW_ACTIVITY_GEN_FROM_ASC_JOB', FALSE); END;

-- T24_CDMEMO_ACTIVITY_JOB
BEGIN DBMS_SCHEDULER.drop_job('T24RAWOGG.T24_CDMEMO_ACTIVITY_GEN_FROM_ACC_JOB', FALSE); END;
BEGIN DBMS_SCHEDULER.drop_job('T24RAWOGG.T24_CDMEMO_ACTIVITY_GEN_FROM_ARR_JOB', FALSE); END;
BEGIN DBMS_SCHEDULER.drop_job('T24RAWOGG.T24_CDMEMO_ACTIVITY_GEN_FROM_ADL_JOB', FALSE); END;
BEGIN DBMS_SCHEDULER.drop_job('T24RAWOGG.T24_CDMEMO_ACTIVITY_GEN_FROM_ECB_JOB', FALSE); END;

BEGIN DBMS_SCHEDULER.stop_job('T24RAWOGG.T24_CDMEMO_ACTIVITY_GEN_FROM_ACC_JOB', FALSE); END;
BEGIN DBMS_SCHEDULER.stop_job('T24RAWOGG.T24_CDMEMO_ACTIVITY_GEN_FROM_ARR_JOB', FALSE); END;
BEGIN DBMS_SCHEDULER.stop_job('T24RAWOGG.T24_CDMEMO_ACTIVITY_GEN_FROM_ADL_JOB', FALSE); END;
BEGIN DBMS_SCHEDULER.stop_job('T24RAWOGG.T24_CDMEMO_ACTIVITY_GEN_FROM_ECB_JOB', FALSE); END;

BEGIN DBMS_SCHEDULER.run_job('T24RAWOGG.T24_CDMEMO_ACTIVITY_GEN_FROM_ACC_JOB', FALSE); END;
BEGIN DBMS_SCHEDULER.run_job('T24RAWOGG.T24_CDMEMO_ACTIVITY_GEN_FROM_ARR_JOB', FALSE); END;
BEGIN DBMS_SCHEDULER.run_job('T24RAWOGG.T24_CDMEMO_ACTIVITY_GEN_FROM_ADL_JOB', FALSE); END;
BEGIN DBMS_SCHEDULER.run_job('T24RAWOGG.T24_CDMEMO_ACTIVITY_GEN_FROM_ECB_JOB', FALSE); END;

-- STATUS
SELECT JOB_NAME, STATE, LAST_START_DATE, NEXT_RUN_DATE, RUN_COUNT, FAILURE_COUNT
FROM USER_SCHEDULER_JOBS;

-- ERROR
SELECT JOB_NAME, ACTUAL_START_DATE, RUN_DURATION, ERRORS
FROM USER_SCHEDULER_JOB_RUN_DETAILS WHERE STATUS = 'FAILED'
AND ACTUAL_START_DATE > TO_TIMESTAMP('2025-09-27 00:00:00.000', 'YYYY-MM-DD HH24:MI:SS.FF3')
ORDER BY ACTUAL_START_DATE DESC;
