SELECT
	'T24_CDMEMO_ACTIVITY' AS TABLE_NAME,
    COUNT(*) AS TOTAL_RECORDS,
    PERCENTILE_CONT(0.10) WITHIN GROUP (ORDER BY LATENCY) AS P10_LATENCY,
    PERCENTILE_CONT(0.25) WITHIN GROUP (ORDER BY LATENCY) AS P25_LATENCY,
    PERCENTILE_CONT(0.50) WITHIN GROUP (ORDER BY LATENCY) AS P50_LATENCY,
    PERCENTILE_CONT(0.75) WITHIN GROUP (ORDER BY LATENCY) AS P75_LATENCY,
    PERCENTILE_CONT(0.90) WITHIN GROUP (ORDER BY LATENCY) AS P90_LATENCY,
    PERCENTILE_CONT(0.99) WITHIN GROUP (ORDER BY LATENCY) AS P99_LATENCY
FROM (
SELECT
    (   EXTRACT(DAY    FROM DIFF) * 86400
      + EXTRACT(HOUR   FROM DIFF) * 3600
      + EXTRACT(MINUTE FROM DIFF) * 60
      + EXTRACT(SECOND FROM DIFF)
    ) AS LATENCY
FROM (
    SELECT (CHANGED_TIME - COMMIT_TS) AS DIFF
    FROM T24_CDMEMO_ACTIVITY
    WHERE CHANGED_TIME
    > TIMESTAMP '2025-10-18 19:30:00.000'
--	BETWEEN TIMESTAMP '2025-10-10 00:00:00.000' AND TIMESTAMP '2025-10-11 00:00:00.000'
--	AND EXTRACT(SECOND FROM (CHANGED_TIME - REPLICAT_TS)) > 1
))
UNION ALL
SELECT
	'T24_CDTNEW_ACTIVITY' AS TABLE_NAME,
    COUNT(*) AS TOTAL_RECORDS,
    PERCENTILE_CONT(0.10) WITHIN GROUP (ORDER BY LATENCY) AS P10_LATENCY,
    PERCENTILE_CONT(0.25) WITHIN GROUP (ORDER BY LATENCY) AS P25_LATENCY,
    PERCENTILE_CONT(0.50) WITHIN GROUP (ORDER BY LATENCY) AS P50_LATENCY,
    PERCENTILE_CONT(0.75) WITHIN GROUP (ORDER BY LATENCY) AS P75_LATENCY,
    PERCENTILE_CONT(0.90) WITHIN GROUP (ORDER BY LATENCY) AS P90_LATENCY,
    PERCENTILE_CONT(0.99) WITHIN GROUP (ORDER BY LATENCY) AS P99_LATENCY
FROM (
SELECT
    (   EXTRACT(DAY    FROM DIFF) * 86400
      + EXTRACT(HOUR   FROM DIFF) * 3600
      + EXTRACT(MINUTE FROM DIFF) * 60
      + EXTRACT(SECOND FROM DIFF)
    ) AS LATENCY
FROM (
    SELECT (CHANGED_TIME - COMMIT_TS) AS DIFF
    FROM T24_CDTNEW_ACTIVITY
    WHERE CHANGED_TIME
    > TIMESTAMP '2025-10-18 19:30:00.000'
--	BETWEEN TIMESTAMP '2025-10-10 00:00:00.000' AND TIMESTAMP '2025-10-11 00:00:00.000'
--	AND EXTRACT(SECOND FROM (CHANGED_TIME - REPLICAT_TS)) > 1
))
UNION ALL
SELECT
	'T24_DDMEMO_ACTIVITY' AS TABLE_NAME,
    COUNT(*) AS TOTAL_RECORDS,
    PERCENTILE_CONT(0.10) WITHIN GROUP (ORDER BY LATENCY) AS P10_LATENCY,
    PERCENTILE_CONT(0.25) WITHIN GROUP (ORDER BY LATENCY) AS P25_LATENCY,
    PERCENTILE_CONT(0.50) WITHIN GROUP (ORDER BY LATENCY) AS P50_LATENCY,
    PERCENTILE_CONT(0.75) WITHIN GROUP (ORDER BY LATENCY) AS P75_LATENCY,
    PERCENTILE_CONT(0.90) WITHIN GROUP (ORDER BY LATENCY) AS P90_LATENCY,
    PERCENTILE_CONT(0.99) WITHIN GROUP (ORDER BY LATENCY) AS P99_LATENCY
FROM (
SELECT
    (   EXTRACT(DAY    FROM DIFF) * 86400
      + EXTRACT(HOUR   FROM DIFF) * 3600
      + EXTRACT(MINUTE FROM DIFF) * 60
      + EXTRACT(SECOND FROM DIFF)
    ) AS LATENCY
FROM (
    SELECT (CHANGED_TIME - COMMIT_TS) AS DIFF
    FROM T24_DDMEMO_ACTIVITY
    WHERE CHANGED_TIME
    > TIMESTAMP '2025-10-18 19:30:00.000'
--	BETWEEN TIMESTAMP '2025-10-10 00:00:00.000' AND TIMESTAMP '2025-10-11 00:00:00.000'
--	AND EXTRACT(SECOND FROM (CHANGED_TIME - REPLICAT_TS)) > 1
))
UNION ALL
SELECT
	'T24_DDTNEW_ACTIVITY' AS TABLE_NAME,
    COUNT(*) AS TOTAL_RECORDS,
    PERCENTILE_CONT(0.10) WITHIN GROUP (ORDER BY LATENCY) AS P10_LATENCY,
    PERCENTILE_CONT(0.25) WITHIN GROUP (ORDER BY LATENCY) AS P25_LATENCY,
    PERCENTILE_CONT(0.50) WITHIN GROUP (ORDER BY LATENCY) AS P50_LATENCY,
    PERCENTILE_CONT(0.75) WITHIN GROUP (ORDER BY LATENCY) AS P75_LATENCY,
    PERCENTILE_CONT(0.90) WITHIN GROUP (ORDER BY LATENCY) AS P90_LATENCY,
    PERCENTILE_CONT(0.99) WITHIN GROUP (ORDER BY LATENCY) AS P99_LATENCY
FROM (
SELECT
    (   EXTRACT(DAY    FROM DIFF) * 86400
      + EXTRACT(HOUR   FROM DIFF) * 3600
      + EXTRACT(MINUTE FROM DIFF) * 60
      + EXTRACT(SECOND FROM DIFF)
    ) AS LATENCY
FROM (
    SELECT (CHANGED_TIME - COMMIT_TS) AS DIFF
    FROM T24_DDTNEW_ACTIVITY
    WHERE CHANGED_TIME
    > TIMESTAMP '2025-10-18 19:30:00.000'
--	BETWEEN TIMESTAMP '2025-10-10 00:00:00.000' AND TIMESTAMP '2025-10-11 00:00:00.000'
--	AND EXTRACT(SECOND FROM (CHANGED_TIME - REPLICAT_TS)) > 1
))
UNION ALL
SELECT
	'T24_LNMEMO_ACTIVITY' AS TABLE_NAME,
    COUNT(*) AS TOTAL_RECORDS,
    PERCENTILE_CONT(0.10) WITHIN GROUP (ORDER BY LATENCY) AS P10_LATENCY,
    PERCENTILE_CONT(0.25) WITHIN GROUP (ORDER BY LATENCY) AS P25_LATENCY,
    PERCENTILE_CONT(0.50) WITHIN GROUP (ORDER BY LATENCY) AS P50_LATENCY,
    PERCENTILE_CONT(0.75) WITHIN GROUP (ORDER BY LATENCY) AS P75_LATENCY,
    PERCENTILE_CONT(0.90) WITHIN GROUP (ORDER BY LATENCY) AS P90_LATENCY,
    PERCENTILE_CONT(0.99) WITHIN GROUP (ORDER BY LATENCY) AS P99_LATENCY
FROM (
SELECT
    (   EXTRACT(DAY    FROM DIFF) * 86400
      + EXTRACT(HOUR   FROM DIFF) * 3600
      + EXTRACT(MINUTE FROM DIFF) * 60
      + EXTRACT(SECOND FROM DIFF)
    ) AS LATENCY
FROM (
    SELECT (CHANGED_TIME - COMMIT_TS) AS DIFF
    FROM T24_LNMEMO_ACTIVITY
    WHERE CHANGED_TIME
    > TIMESTAMP '2025-10-18 19:30:00.000'
--	BETWEEN TIMESTAMP '2025-10-10 00:00:00.000' AND TIMESTAMP '2025-10-11 00:00:00.000'
--	AND EXTRACT(SECOND FROM (CHANGED_TIME - REPLICAT_TS)) > 1
))
UNION ALL
SELECT
	'T24_LNTNEW_ACTIVITY' AS TABLE_NAME,
    COUNT(*) AS TOTAL_RECORDS,
    PERCENTILE_CONT(0.10) WITHIN GROUP (ORDER BY LATENCY) AS P10_LATENCY,
    PERCENTILE_CONT(0.25) WITHIN GROUP (ORDER BY LATENCY) AS P25_LATENCY,
    PERCENTILE_CONT(0.50) WITHIN GROUP (ORDER BY LATENCY) AS P50_LATENCY,
    PERCENTILE_CONT(0.75) WITHIN GROUP (ORDER BY LATENCY) AS P75_LATENCY,
    PERCENTILE_CONT(0.90) WITHIN GROUP (ORDER BY LATENCY) AS P90_LATENCY,
    PERCENTILE_CONT(0.99) WITHIN GROUP (ORDER BY LATENCY) AS P99_LATENCY
FROM (
SELECT
    (   EXTRACT(DAY    FROM DIFF) * 86400
      + EXTRACT(HOUR   FROM DIFF) * 3600
      + EXTRACT(MINUTE FROM DIFF) * 60
      + EXTRACT(SECOND FROM DIFF)
    ) AS LATENCY
FROM (
    SELECT (CHANGED_TIME - COMMIT_TS) AS DIFF
    FROM T24_LNTNEW_ACTIVITY
    WHERE CHANGED_TIME
    > TIMESTAMP '2025-10-18 19:30:00.000'
--	BETWEEN TIMESTAMP '2025-10-10 00:00:00.000' AND TIMESTAMP '2025-10-11 00:00:00.000'
--	AND EXTRACT(SECOND FROM (CHANGED_TIME - REPLICAT_TS)) > 1
))
UNION ALL
SELECT
	'T24_TMTRAN' AS TABLE_NAME,
    COUNT(*) AS TOTAL_RECORDS,
    PERCENTILE_CONT(0.10) WITHIN GROUP (ORDER BY LATENCY) AS P10_LATENCY,
    PERCENTILE_CONT(0.25) WITHIN GROUP (ORDER BY LATENCY) AS P25_LATENCY,
    PERCENTILE_CONT(0.50) WITHIN GROUP (ORDER BY LATENCY) AS P50_LATENCY,
    PERCENTILE_CONT(0.75) WITHIN GROUP (ORDER BY LATENCY) AS P75_LATENCY,
    PERCENTILE_CONT(0.90) WITHIN GROUP (ORDER BY LATENCY) AS P90_LATENCY,
    PERCENTILE_CONT(0.99) WITHIN GROUP (ORDER BY LATENCY) AS P99_LATENCY
FROM (
SELECT
    (   EXTRACT(DAY    FROM DIFF) * 86400
      + EXTRACT(HOUR   FROM DIFF) * 3600
      + EXTRACT(MINUTE FROM DIFF) * 60
      + EXTRACT(SECOND FROM DIFF)
    ) AS LATENCY
FROM (
    SELECT (CHANGED_TIME - COMMIT_TS) AS DIFF
    FROM T24_TMTRAN
    WHERE CHANGED_TIME
    > TIMESTAMP '2025-10-18 19:30:00.000'
--	BETWEEN TIMESTAMP '2025-10-10 00:00:00.000' AND TIMESTAMP '2025-10-11 00:00:00.000'
--	AND EXTRACT(SECOND FROM (CHANGED_TIME - COMMIT_TS)) > 1
));
