SELECT
    ACCTNO,
    TO_CHAR(COMMIT_TS, 'YYYY-MM-DD HH24:MI:SS.FF3') AS COMMIT_TS,
    TO_CHAR(REPLICAT_TS, 'YYYY-MM-DD HH24:MI:SS.FF3') AS REPLICAT_TS,
    TO_CHAR(MAPPED_TS, 'YYYY-MM-DD HH24:MI:SS.FF3') AS MAPPED_TS,
    TO_CHAR(CHANGED_TIME, 'YYYY-MM-DD HH24:MI:SS.FF3') AS CHANGED_TIME,
    EXTRACT(SECOND FROM (CHANGED_TIME - REPLICAT_TS)) AS LATENCY,
    CALL_CDC
FROM T24_LNMEMO_ACTIVITY
WHERE CHANGED_TIME
    > TIMESTAMP '2025-09-10 00:00:00.000'
--	BETWEEN TIMESTAMP '2025-10-02 14:30:00.000' AND TIMESTAMP '2025-10-02 15:30:00.000'
--	AND EXTRACT(SECOND FROM (CHANGED_TIME - REPLICAT_TS)) > 1
ORDER BY CHANGED_TIME DESC
--ORDER BY LATENCY DESC
FETCH FIRST 10 ROWS ONLY;

SELECT
    COUNT(*) AS TOTAL_RECORDS,
    PERCENTILE_CONT(0.10) WITHIN GROUP (ORDER BY LATENCY) AS P10_LATENCY,
    PERCENTILE_CONT(0.25) WITHIN GROUP (ORDER BY LATENCY) AS P25_LATENCY,
    PERCENTILE_CONT(0.50) WITHIN GROUP (ORDER BY LATENCY) AS P50_LATENCY,
    PERCENTILE_CONT(0.75) WITHIN GROUP (ORDER BY LATENCY) AS P75_LATENCY,
    PERCENTILE_CONT(0.90) WITHIN GROUP (ORDER BY LATENCY) AS P90_LATENCY,
    PERCENTILE_CONT(0.99) WITHIN GROUP (ORDER BY LATENCY) AS P99_LATENCY
FROM (
SELECT
    (   EXTRACT(DAY    FROM DIFF) * 86400
      + EXTRACT(HOUR   FROM DIFF) * 3600
      + EXTRACT(MINUTE FROM DIFF) * 60
      + EXTRACT(SECOND FROM DIFF)
    ) AS LATENCY
FROM (
    SELECT (CHANGED_TIME - REPLICAT_TS) AS DIFF
    FROM T24_LNMEMO_ACTIVITY
    WHERE CHANGED_TIME
    > TIMESTAMP '2025-09-10 00:00:00.000'
--	BETWEEN TIMESTAMP '2025-10-02 14:30:00.000' AND TIMESTAMP '2025-10-02 15:30:00.000'
--	AND EXTRACT(SECOND FROM (CHANGED_TIME - REPLICAT_TS)) > 1
));

SELECT 'FMSB_ACC_MAPPED' AS TABLE_NAME, COUNT(*) AS TABLE_COUNT
FROM FMSB_ACC_MAPPED
UNION ALL
SELECT 'FMSB_ARR_LNMEMO', COUNT(*)
FROM FMSB_ARR_LNMEMO
UNION ALL
SELECT 'FMSB_ECB_MAPPED', COUNT(*)
FROM FMSB_ECB_MAPPED
UNION ALL
SELECT 'F_DAT_MAPPED', COUNT(*)
FROM F_DAT_MAPPED
UNION ALL
SELECT 'FMSB_LMT_MAPPED', COUNT(*)
FROM FMSB_LMT_MAPPED
UNION ALL
SELECT 'FMSB_BIL_LNMEMO', COUNT(*)
FROM FMSB_BIL_LNMEMO
UNION ALL
SELECT 'T24_LNMEMO_ACTIVITY_ACC', COUNT(*)
FROM T24_LNMEMO_ACTIVITY_ACC
UNION ALL
SELECT 'T24_LNMEMO_ACTIVITY_ARR', COUNT(*)
FROM T24_LNMEMO_ACTIVITY_ARR
UNION ALL
SELECT 'T24_LNMEMO_ACTIVITY_BIL', COUNT(*)
FROM T24_LNMEMO_ACTIVITY_BIL
UNION ALL
SELECT 'T24_LNMEMO_ACTIVITY_ECB', COUNT(*)
FROM T24_LNMEMO_ACTIVITY_ECB
UNION ALL
SELECT 'T24_LNMEMO_ACTIVITY', COUNT(*)
FROM T24_LNMEMO_ACTIVITY;

SELECT * FROM T24_LNMEMO_ACTIVITY
--WHERE ACCTNO = 30000000793
ORDER BY CHANGED_TIME DESC
FETCH FIRST 10 ROWS ONLY;

SELECT SUM(BILPRN_AMT) AS BILPRN, SUM(BILINT_AMT) AS BILINT, SUM(BILLC_AMT) AS BILLC FROM FMSB_BIL_LNMEMO
WHERE ARRANGEMENT_ID = (SELECT RECID FROM FMSB_ARR_LNMEMO WHERE LINKED_APPL_ID = '30000002217');

ALTER SESSION SET NLS_NUMERIC_CHARACTERS = '.,';

BEGIN
    T24_LNMEMO_ACTIVITY_PKG.GEN_FROM_BIL_PROC;
END;
