ALTER SESSION SET NLS_NUMERIC_CHARACTERS = '.,';

SELECT
    ACCTNO,
    COMMIT_TS,
    REPLICAT_TS,
    MAPPED_TS,
    CHANGED_TIME,
    (   EXTRACT(DAY    FROM (CHANGED_TIME - REPLICAT_TS)) * 86400
      + EXTRACT(HOUR   FROM (CHANGED_TIME - REPLICAT_TS)) * 3600
      + EXTRACT(MINUTE FROM (CHANGED_TIME - REPLICAT_TS)) * 60
      + EXTRACT(SECOND FROM (CHANGED_TIME - REPLICAT_TS))
    ) AS LATENCY,
    CALL_CDC
FROM T24_LNMEMO_ACTIVITY
WHERE CHANGED_TIME
    > TIMESTAMP '2025-10-10 00:00:00.000'
--	BETWEEN TIMESTAMP '2025-10-10 00:00:00.000' AND TIMESTAMP '2025-10-11 00:00:00.000'
--	AND ( EXTRACT(DAY    FROM (CHANGED_TIME - REPLICAT_TS)) * 86400
--	    + EXTRACT(HOUR   FROM (CHANGED_TIME - REPLICAT_TS)) * 3600
--	    + EXTRACT(MINUTE FROM (CHANGED_TIME - REPLICAT_TS)) * 60
--	    + EXTRACT(SECOND FROM (CHANGED_TIME - REPLICAT_TS)) ) > 1
--ORDER BY LATENCY DESC
ORDER BY CHANGED_TIME DESC
FETCH FIRST 10 ROWS ONLY;

SELECT SUM(BILPRN_AMT) AS BILPRN, SUM(BILINT_AMT) AS BILINT, SUM(BILLC_AMT) AS BILLC FROM FMSB_BIL_LNMEMO
WHERE ARRANGEMENT_ID = (SELECT RECID FROM FMSB_ARR_LNMEMO WHERE LINKED_APPL_ID = '30000002217');

SELECT * FROM (
SELECT RECID, WINDOW_ID, OP_TYPE, COMMIT_TS, 'ACC' AS CALL_CDC FROM FMSB_ACC_MAPPED
UNION ALL
SELECT RECID, WINDOW_ID, OP_TYPE, COMMIT_TS, 'ARR' FROM FMSB_ARR_LNMEMO
UNION ALL
SELECT RECID, WINDOW_ID, OP_TYPE, COMMIT_TS, 'ECB' FROM FMSB_ECB_MAPPED )
WHERE WINDOW_ID = 157257176201230147158748

SELECT A.CHANGED_TIME, A.MAPPED_TS, A.REPLICAT_TS, A.COMMIT_TS, A.* FROM T24RAWOGG.T24_LNMEMO_ACTIVITY A
--WHERE A.ACCTNO = 30000121443
ORDER BY A.CHANGED_TIME DESC
FETCH FIRST 10 ROWS ONLY;
SELECT A.CHANGED_TIME, A.* FROM T24RAW.T24_LNMEMO_ACTIVITY A
--WHERE A.ACCTNO = 30000121443
ORDER BY A.CHANGED_TIME DESC
FETCH FIRST 10 ROWS ONLY;

BEGIN T24_LNMEMO_ACTIVITY_PKG.GEN_FROM_ACC_ARR_ECB_PROC; END;
BEGIN T24_LNMEMO_ACTIVITY_PKG.GEN_FROM_BIL_PROC; END;
BEGIN T24_LNMEMO_ACTIVITY_PKG.GEN_FROM_LMT_PROC; END;

SELECT 'FMSB_ACC_MAPPED' AS TABLE_NAME, COUNT(*) AS TABLE_COUNT
FROM FMSB_ACC_MAPPED
UNION ALL
SELECT 'FMSB_ARR_LNMEMO', COUNT(*)
FROM FMSB_ARR_LNMEMO
UNION ALL
SELECT 'FMSB_ECB_MAPPED', COUNT(*)
FROM FMSB_ECB_MAPPED
UNION ALL
SELECT 'F_DAT_MAPPED', COUNT(*)
FROM F_DAT_MAPPED
UNION ALL
SELECT 'FMSB_LMT_MAPPED', COUNT(*)
FROM FMSB_LMT_MAPPED
UNION ALL
SELECT 'FMSB_BIL_LNMEMO', COUNT(*)
FROM FMSB_BIL_LNMEMO
UNION ALL
SELECT 'T24_LNMEMO_ACTIVITY_ACC_ARR_ECB', COUNT(*)
FROM T24_LNMEMO_ACTIVITY_ACC_ARR_ECB
UNION ALL
SELECT 'T24_LNMEMO_ACTIVITY_BIL', COUNT(*)
FROM T24_LNMEMO_ACTIVITY_BIL
UNION ALL
SELECT 'T24_LNMEMO_ACTIVITY_LMT', COUNT(*)
FROM T24_LNMEMO_ACTIVITY_LMT
UNION ALL
SELECT 'T24_LNMEMO_ACTIVITY', COUNT(*)
FROM T24_LNMEMO_ACTIVITY;

TRUNCATE TABLE T24_LNMEMO_ACTIVITY;
