INSERT INTO T24_LNMEMO_ACTIVITY_ACC_ARR_ECB (WINDOW_ID, JOIN_KEY)
SELECT WINDOW_ID, RECID AS JOIN_KEY FROM V_FMSB_ACC_MAPPED ACC WHERE EXISTS (
            SELECT 1
            FROM V_FMSB_ARR_LNMEMO ARR
            WHERE ARR.LINKED_APPL_ID = ACC.RECID
        );

INSERT INTO T24_LNMEMO_ACTIVITY_ACC_ARR_ECB (WINDOW_ID, JOIN_KEY)
SELECT WINDOW_ID, RECID AS JOIN_KEY FROM V_FMSB_ECB_MAPPED ECB WHERE EXISTS (
            SELECT 1
            FROM V_FMSB_ARR_LNMEMO ARR
            WHERE ARR.LINKED_APPL_ID = ECB.RECID
        );

INSERT INTO T24_LNMEMO_ACTIVITY_ACC_ARR_ECB (WINDOW_ID, JOIN_KEY)
SELECT WINDOW_ID , LINKED_APPL_ID AS JOIN_KEY FROM V_FMSB_ARR_LNMEMO ARR WHERE EXISTS (
            SELECT 1
            FROM V_FMSB_ACC_MAPPED ACC
            WHERE ACC.RECID = ARR.LINKED_APPL_ID
        );

INSERT INTO T24_LNMEMO_ACTIVITY_BIL (WINDOW_ID, ARRANGEMENT_ID)
SELECT WINDOW_ID, ARRANGEMENT_ID FROM V_FMSB_BIL_LNMEMO BIL WHERE EXISTS (
    SELECT 1
    FROM (
        SELECT RECID FROM V_FMSB_ARR_LNMEMO ARR WHERE EXISTS (
            SELECT 1
            FROM V_FMSB_ACC_MAPPED ACC
            WHERE ACC.RECID = ARR.LINKED_APPL_ID
        )
    ) ARR
    WHERE ARR.RECID = BIL.ARRANGEMENT_ID
);
-- ) FETCH FIRST 30000 ROWS ONLY;

INSERT INTO T24_LNMEMO_ACTIVITY_LMT (WINDOW_ID)
SELECT WINDOW_ID FROM V_FMSB_LMT_MAPPED LMT WHERE EXISTS (
    SELECT 1
    FROM (
        SELECT LIMIT_KEY FROM V_FMSB_ACC_MAPPED ACC WHERE EXISTS (
            SELECT 1
            FROM V_FMSB_ARR_LNMEMO ARR
            WHERE ARR.LINKED_APPL_ID = ACC.RECID
        )
    ) ACC
    WHERE ACC.LIMIT_KEY = LMT.RECID
);
