CREATE TABLE T24_CDTNEW_ACTIVITY_ACC
(
    WINDOW_ID NUMBER(25),
    CAPTURED_TIME TIMESTAMP(3) DEFAULT SYSTIMESTAMP
)
    INMEMORY MEMCOMPRESS FOR QUERY LOW
    PRIORITY CRITICAL
    TABLESPACE T24RAWOGG;