CREATE TABLE FMSB_ARC_DDTNEW
(
    RECID          VARCHAR2(255),
    WINDOW_ID      NUMBER(25),
    OP_TYPE        CHAR(1),
    COMMIT_TS      TIMESTAMP(3),
    REPLICAT_TS    TIMESTAMP(3),
    MAPPED_TS      TIMESTAMP(3),
	ARRANGEMENT    VARCHAR2(255), 
	ACTIVITY       VARCHAR2(255),
	TRADE_DATE     DATE,
	DATE_TIME      VARCHAR2(255),
    CONSTRAINT PK_FMSB_ARC_DDTNEW PRIMARY KEY (RECID)
)
    TABLESPACE T24RAWOGG;

CREATE INDEX IDX_FMSB_ARC_DDTNEW_OP_TYPE
    ON FMSB_ARC_DDTNEW (OP_TYPE)
    TABLESPACE T24RAWOGG_IDX;

CREATE INDEX IDX_FMSB_ARC_DDTNEW_AARRANGEMENT
    ON FMSB_ARC_DDTNEW (ARRANGEMENT)
    TABLESPACE T24RAWOGG_IDX;