CREATE TABLE FMSB_ARR_DD
(
    RECID              VARCHAR2(255),
    WINDOW_ID          NUMBER(25),
    COMMIT_TS          TIMESTAMP(3),
    REPLICAT_TS        TIMESTAMP(3),
    MAPPED_TS          TIMESTAMP(3),
    ARR_STATUS         VARCHAR2(255),
    PRODUCT            VARCHAR2(255),
    PRODUCT_STATUS     VARCHAR2(255),
    LINKED_APPL_ID     VARCHAR2(255),
    ORIG_CONTRACT_DATE DATE,
    START_DATE         DATE,
    CONSTRAINT PK_FMSB_ARR_DD PRIMARY KEY (RECID)
)
    TABLESPACE T24DB_OGGDS;

CREATE INDEX IDX_FMSB_ARR_DD_REC_WIN_ID
    ON FMSB_ARR_DD (RECID, WINDOW_ID)
    TABLESPACE T24DB_OGGDS;

CREATE INDEX IDX_FMSB_ARR_DD_MAPPED_WINDOW_ID
    ON FMSB_ARR_DD (WINDOW_ID)
    TABLESPACE T24DB_OGGDS;

CREATE INDEX IDX_FMSB_ARR_DD_LINKED_APPL_ID
    ON FMSB_ARR_DD (LINKED_APPL_ID)
    TABLESPACE T24DB_OGGDS;


