CREATE TABLE T24_DDMEMO_ACTIVITY_ADL 
(
    WINDOW_ID NUMBER(25),
    CAPTURED_TIME TIMESTAMP(3) DEFAULT SYSTIMESTAMP
)
    INMEMORY MEMCOMPRESS FOR QUERY LOW
    PRIORITY CRITICAL
    TABLESPACE T24RAWOGG;