CREATE TABLE T24_DDMEMO_ACTIVITY_ACC 
(
    RECID     VARCHAR2(255),
    WINDOW_ID NUMBER(25)
)
    INMEMORY MEMCOMPRESS FOR QUERY LOW
    PRIORITY CRITICAL
    TABLESPACE T24RAWOGG;

CREATE INDEX IDX_T24_DDMEMO_ACTIVITY_ACC_REC_WIN_ID 
    ON T24_DDMEMO_ACTIVITY_ACC (RECID, WINDOW_ID)
    TABLESPACE T24RAWOGG_IDX;

CREATE INDEX IDX_T24_DDMEMO_ACTIVITY_ACC_WINDOW_ID
    ON T24_DDMEMO_ACTIVITY_ACC (WINDOW_ID)
    TABLESPACE T24RAWOGG_IDX;
