CREATE OR REPLACE PACKAGE T24RAWOGG.T24_UTILS_PKG IS

    FUNCTION GET_LAST_VAL_FUNC(
        P_INPUT IN VARCHAR2
    ) RETURN VARCHAR2;

    FUNCTION GET_STR_VAL_BY_POS_FUNC(
        P_INPUT IN VARCHAR2,
        P_POS IN VARCHAR2
    ) RETURN VARCHAR2;

    FUNCTION GET_NUM_VAL_BY_POS_FUNC(
        P_INPUT IN VARCHAR2,
        P_POS IN VARCHAR2
    ) RETURN NUMBER;

    FUNCTION MEMO_EXCEED_FUNC(
        P_INPUT IN NUMBER,
        P_PRECISION IN NUMBER,
        P_SCALE IN NUMBER
    ) RETURN NUMBER;

    FUNCTION GET_DAY_TYPE_FUNC(
        P_INPUT IN VARCHAR2
    ) RETURN VARCHAR2;

    FUNCTION FIND_NEXT_WORKING_DAY_FUNC(
        P_INPUT IN VARCHAR2
    ) RETURN VARCHAR2;
END T24_UTILS_PKG;

CREATE OR REPLACE PACKAGE BODY T24RAWOGG.T24_UTILS_PKG IS

    FUNCTION GET_LAST_VAL_FUNC(
        P_INPUT IN VARCHAR2
    ) RETURN VARCHAR2 IS
    BEGIN
        RETURN SUBSTR(P_INPUT, INSTR(P_INPUT, ':', -1) + 1);
    END GET_LAST_VAL_FUNC;

    FUNCTION GET_STR_VAL_BY_POS_FUNC(
        P_INPUT IN VARCHAR2,
        P_POS IN VARCHAR2
    ) RETURN VARCHAR2 IS
        V_IDX    PLS_INTEGER := INSTR(P_INPUT, P_POS);
        V_START  PLS_INTEGER;
        V_END    PLS_INTEGER;
        V_RESULT VARCHAR2(255);
    BEGIN
        IF V_IDX = 0 THEN
            RETURN NULL;
        END IF;

        V_START := V_IDX + LENGTH(P_POS);
        V_END := INSTR(P_INPUT, '#', V_START);

        IF V_END = 0 THEN
            V_RESULT := SUBSTR(P_INPUT, V_START);
        ELSE
            V_RESULT := SUBSTR(P_INPUT, V_START, V_END - V_START);
        END IF;

        RETURN V_RESULT;
    END GET_STR_VAL_BY_POS_FUNC;

    FUNCTION GET_NUM_VAL_BY_POS_FUNC(
        P_INPUT IN VARCHAR2,
        P_POS IN VARCHAR2
    ) RETURN NUMBER IS
        V_IDX    PLS_INTEGER := INSTR(P_INPUT, P_POS);
        V_START  PLS_INTEGER;
        V_END    PLS_INTEGER;
        V_RESULT VARCHAR2(20);
    BEGIN
        IF V_IDX = 0 THEN
            RETURN 0;
        END IF;

        V_START := V_IDX + LENGTH(P_POS);
        V_END := INSTR(P_INPUT, '#', V_START);

        IF V_END = 0 THEN
            V_RESULT := SUBSTR(P_INPUT, V_START);
        ELSE
            V_RESULT := SUBSTR(P_INPUT, V_START, V_END - V_START);
        END IF;

        RETURN NVL(TO_NUMBER(V_RESULT), 0);
    END GET_NUM_VAL_BY_POS_FUNC;

    FUNCTION MEMO_EXCEED_FUNC(
        P_INPUT IN NUMBER,
        P_PRECISION IN NUMBER,
        P_SCALE IN NUMBER
    ) RETURN NUMBER IS
    BEGIN
        IF ABS(P_INPUT) < POWER(10, P_PRECISION - P_SCALE) THEN
            RETURN P_INPUT;
        ELSE
            RETURN 0;
        END IF;
    END MEMO_EXCEED_FUNC;

    FUNCTION GET_DAY_TYPE_FUNC (
        P_INPUT IN VARCHAR2
    ) RETURN VARCHAR2 IS
        V_DATE   DATE;
        V_YEAR   VARCHAR2(10);
        V_MONTH  VARCHAR2(10);
        V_DAY    NUMBER;
        V_DAYS   VARCHAR2(31);
        V_SQL    VARCHAR2(500);
        V_RESULT VARCHAR2(10);
    BEGIN
        IF P_INPUT IS NULL THEN 
            RETURN NULL;
        END IF;

        V_DATE := TO_DATE(P_INPUT, 'YYYYMMDD');

        V_YEAR  := TO_CHAR(V_DATE, 'YYYY');
        V_MONTH := TO_CHAR(V_DATE, 'MM');
        V_DAY   := TO_NUMBER(TO_CHAR(V_DATE, 'DD'));

        V_SQL :=
            'SELECT MTH_' || V_MONTH || '_TABLE ' ||
            'FROM F_HOLIDAY_MAPPED ' ||
            'WHERE RECID = :1';

        EXECUTE IMMEDIATE V_SQL
            INTO V_DAYS
            USING 'VN00' || V_YEAR;

        V_RESULT := SUBSTR(V_DAYS, V_DAY, 1);

        RETURN V_RESULT;

    END GET_DAY_TYPE_FUNC;

    FUNCTION FIND_NEXT_WORKING_DAY_FUNC (
        P_INPUT IN VARCHAR2
    ) RETURN NUMBER IS
        V_DATE      DATE;
        V_NEXT_DATE DATE;
    BEGIN
        V_DATE := TO_DATE(P_INPUT, 'YYYYMMDD');

        V_NEXT_DATE := V_DATE + 1;

        IF GET_DAY_TYPE_FUNC(TO_CHAR(V_NEXT_DATE, 'YYYYMMDD')) = 'W' THEN
            RETURN 1;
        END IF;

        V_DATE := V_NEXT_DATE;

        LOOP
            V_DATE := V_DATE + 1;

            IF GET_DAY_TYPE_FUNC(TO_CHAR(V_DATE, 'YYYYMMDD')) = 'W' THEN
                RETURN TO_NUMBER(TO_CHAR(V_DATE, 'DD'));
            END IF;

        END LOOP;
        
    END FIND_NEXT_WORKING_DAY_FUNC;

END T24_UTILS_PKG;
