CREATE OR REPLACE PACKAGE T24_DDMEMO_ACTIVITY_PKG IS

    FUNCTION CALC_HOLD_VAL_FUNC(
        P_FROM_DATE     IN VARCHAR2,
        P_TODAY         IN VARCHAR2,
        P_LOCKED_AMOUNT IN VARCHAR2
    ) RETURN NUMBER;

    FUNCTION CALC_CBAL_VAL_FUNC(
        P_CURR_ASSET_TYPE IN VARCHAR2,
        P_OPEN_BALANCE    IN VARCHAR2,
        P_CREDIT_MVMT     IN VARCHAR2,
        P_DEBIT_MVMT      IN VARCHAR2
    ) RETURN NUMBER;

    FUNCTION CALC_ACCRUE_VAL_FUNC(
        P_CURR_ASSET_TYPE IN VARCHAR2,
        P_OPEN_BALANCE    IN VARCHAR2,
        P_CREDIT_MVMT     IN VARCHAR2,
        P_DEBIT_MVMT      IN VARCHAR2
    ) RETURN NUMBER;

    PROCEDURE GEN_FROM_ACC_PROC;

    PROCEDURE GEN_FROM_ARR_PROC;

    PROCEDURE GEN_FROM_ECB_PROC;

    PROCEDURE GEN_FROM_ADL_PROC;

    PROCEDURE GEN_FROM_LMT_PROC;

END T24_DDMEMO_ACTIVITY_PKG;

CREATE OR REPLACE PACKAGE BODY T24_DDMEMO_ACTIVITY_PKG IS

    FUNCTION CALC_HOLD_VAL_FUNC(
        P_FROM_DATE     IN VARCHAR2,
        P_TODAY         IN VARCHAR2,
        P_LOCKED_AMOUNT IN VARCHAR2
    ) RETURN NUMBER IS
        V_HOLD          NUMBER;
        V_PAST          NUMBER;
        V_START         PLS_INTEGER := 1;
        V_LEN           PLS_INTEGER := LENGTH(P_FROM_DATE);
        V_COLON_IDX     PLS_INTEGER;
        V_HASH_IDX      PLS_INTEGER;
        V_M_VAL         VARCHAR2(6);
        V_FROM_DATE     VARCHAR2(8);
        V_LOCKED_AMOUNT NUMBER;
    BEGIN
        IF P_LOCKED_AMOUNT IS NULL THEN
            RETURN 0;
        END IF;

        V_HOLD := TO_NUMBER(T24_UTILS_PKG.GET_LAST_VAL_FUNC(P_LOCKED_AMOUNT));

        WHILE V_START <= V_LEN LOOP
            V_COLON_IDX := INSTR(P_FROM_DATE, ':', V_START) + 1;
            V_HASH_IDX  := INSTR(P_FROM_DATE, '#', V_COLON_IDX);

            IF V_HASH_IDX = 0 THEN
                V_HASH_IDX := V_LEN + 1;
            END IF;

            V_M_VAL         := SUBSTR(P_FROM_DATE, V_START, V_COLON_IDX - V_START);
            V_FROM_DATE     := SUBSTR(P_FROM_DATE, V_COLON_IDX, V_HASH_IDX - V_COLON_IDX);
            V_LOCKED_AMOUNT := T24_UTILS_PKG.GET_NUM_VAL_BY_POS_FUNC(P_LOCKED_AMOUNT, V_M_VAL);

            IF V_FROM_DATE > P_TODAY THEN
                V_HOLD := GREATEST(V_HOLD, V_LOCKED_AMOUNT);
            ELSE
                V_PAST := V_LOCKED_AMOUNT;
            END IF;

            V_START := V_HASH_IDX;
        END LOOP;

        RETURN GREATEST(V_HOLD, NVL(V_PAST, V_HOLD));
    END CALC_HOLD_VAL_FUNC;

    FUNCTION CALC_CBAL_VAL_FUNC(
        P_CURR_ASSET_TYPE IN VARCHAR2,
        P_OPEN_BALANCE    IN VARCHAR2,
        P_CREDIT_MVMT     IN VARCHAR2,
        P_DEBIT_MVMT      IN VARCHAR2
    ) RETURN NUMBER IS
        V_CBAL              NUMBER := 0;
        V_START             PLS_INTEGER := 1;
        V_LEN               PLS_INTEGER := LENGTH(P_CURR_ASSET_TYPE);
        V_COLON_IDX         PLS_INTEGER;
        V_HASH_IDX          PLS_INTEGER;
        V_M_VAL             VARCHAR2(6);
        V_CURR_ASSET_TYPE   VARCHAR2(50);
    BEGIN
        IF P_CURR_ASSET_TYPE IS NULL THEN
            RETURN 0;
        END IF;

        WHILE V_START <= V_LEN LOOP
            V_COLON_IDX := INSTR(P_CURR_ASSET_TYPE, ':', V_START) + 1;
            V_HASH_IDX  := INSTR(P_CURR_ASSET_TYPE, '#', V_COLON_IDX);

            IF V_HASH_IDX = 0 THEN
                V_HASH_IDX := V_LEN + 1;
            END IF;

            V_M_VAL            := SUBSTR(P_CURR_ASSET_TYPE, V_START, V_COLON_IDX - V_START);
            V_CURR_ASSET_TYPE  := SUBSTR(P_CURR_ASSET_TYPE, V_COLON_IDX, V_HASH_IDX - V_COLON_IDX);

            IF V_CURR_ASSET_TYPE IN ('CREDIT', 'DEBIT') THEN
                V_CBAL := V_CBAL
                    + T24_UTILS_PKG.GET_NUM_VAL_BY_POS_FUNC(P_OPEN_BALANCE, V_M_VAL)
                    + T24_UTILS_PKG.GET_NUM_VAL_BY_POS_FUNC(P_CREDIT_MVMT, V_M_VAL)
                    + T24_UTILS_PKG.GET_NUM_VAL_BY_POS_FUNC(P_DEBIT_MVMT, V_M_VAL);
            END IF;

            V_START := V_HASH_IDX;
        END LOOP;

        RETURN V_CBAL;
    END CALC_CBAL_VAL_FUNC;

    FUNCTION CALC_ACCRUE_VAL_FUNC(
        P_CURR_ASSET_TYPE IN VARCHAR2,
        P_OPEN_BALANCE    IN VARCHAR2,
        P_CREDIT_MVMT     IN VARCHAR2,
        P_DEBIT_MVMT      IN VARCHAR2
    ) RETURN NUMBER IS
        V_ACCRUE            NUMBER := 0;
        V_START             PLS_INTEGER := 1;
        V_LEN               PLS_INTEGER := LENGTH(P_CURR_ASSET_TYPE);
        V_COLON_IDX         PLS_INTEGER;
        V_HASH_IDX          PLS_INTEGER;
        V_M_VAL             VARCHAR2(6);
        V_CURR_ASSET_TYPE   VARCHAR2(50);
    BEGIN
        IF P_CURR_ASSET_TYPE IS NULL THEN
            RETURN 0;
        END IF;

        WHILE V_START <= V_LEN LOOP
            V_COLON_IDX := INSTR(P_CURR_ASSET_TYPE, ':', V_START) + 1;
            V_HASH_IDX  := INSTR(P_CURR_ASSET_TYPE, '#', V_COLON_IDX);

            IF V_HASH_IDX = 0 THEN
                V_HASH_IDX := V_LEN + 1;
            END IF;

            V_M_VAL            := SUBSTR(P_CURR_ASSET_TYPE, V_START, V_COLON_IDX - V_START);
            V_CURR_ASSET_TYPE  := SUBSTR(P_CURR_ASSET_TYPE, V_COLON_IDX, V_HASH_IDX - V_COLON_IDX);

            IF V_CURR_ASSET_TYPE IN (
                'ACCCRINTEREST', 'ACCODCREDITINT', 'PAYCRINTEREST', 'DUEODCREDITINT'
            ) THEN
                V_ACCRUE := V_ACCRUE
                    + T24_UTILS_PKG.GET_NUM_VAL_BY_POS_FUNC(P_OPEN_BALANCE, V_M_VAL)
                    + T24_UTILS_PKG.GET_NUM_VAL_BY_POS_FUNC(P_CREDIT_MVMT, V_M_VAL)
                    + T24_UTILS_PKG.GET_NUM_VAL_BY_POS_FUNC(P_DEBIT_MVMT, V_M_VAL);
            END IF;

            V_START := V_HASH_IDX;
        END LOOP;

        RETURN ABS(V_ACCRUE);
    END CALC_ACCRUE_VAL_FUNC;

    PROCEDURE GEN_FROM_ACC_PROC IS
        V_WINDOW_ID_LIST T_WINDOW_ID_ARRAY;
        V_TODAY          VARCHAR2(8);
    BEGIN
        DELETE FROM T24_DDMEMO_ACTIVITY_ACC CDC
        WHERE EXISTS (
            SELECT 1 FROM FMSB_ACC_MAPPED ACC
            WHERE ACC.RECID = CDC.RECID AND CDC.WINDOW_ID <= ACC.WINDOW_ID
        )
        -- AND ROWNUM <= 5000
        RETURNING CDC.WINDOW_ID BULK COLLECT INTO V_WINDOW_ID_LIST;
    
        SELECT TODAY INTO V_TODAY
        FROM F_DAT_MAPPED
        WHERE RECID = 'VN0011000';

        INSERT INTO T24_DDMEMO_ACTIVITY (
            BRANCH, ACCTNO, ACNAME, CIFNO, STATUS, SCCODE,
            DLA7, DLA6, HOLD, CBAL, ACCRUE, ODLIMT,
            WINDOW_ID, COMMIT_TS, REPLICAT_TS, MAPPED_TS, CALL_CDC
        )
        SELECT
            ACC.CO_CODE,
            TO_NUMBER(ACC.RECID),
            TRIM(ACC.ACNAME),
            TO_NUMBER(ACC.CUSTOMER),
            CASE
                WHEN ARR.ARR_STATUS IN ('CLOSE', 'PENDING.CLOSURE', 'CANCELLED') THEN 2
                WHEN PST.RESTRICTION_TYPE = 'DEBIT' THEN 6
                WHEN PST.RESTRICTION_TYPE = 'ALL' THEN 7
                WHEN ADL.DORMANCY_STATUS IS NOT NULL THEN 9
                WHEN ARR.START_DATE = V_TODAY AND ARR.ARR_STATUS NOT IN ('CLOSE', 'PENDING.CLOSURE') THEN 4
                WHEN ARR.ARR_STATUS IN ('AUTH', 'RESTORE-AUTH') AND ADL.DORMANCY_STATUS IS NULL THEN 1
            END,
            ARR.ACTIVE_PRODUCT,
            (
                SELECT TO_NUMBER(TO_CHAR(MAX_EFF_DAT, 'YYYYDDD'))
                FROM MV_FMSB_ARC_DDMEMO
                WHERE ARRANGEMENT = ARR.RECID
            ),
            (
                SELECT TO_NUMBER(TO_CHAR(MAX_EFF_DAT, 'DDMMYY'))
                FROM MV_FMSB_ARC_DDMEMO
                WHERE ARRANGEMENT = ARR.RECID
            ),
            CALC_HOLD_VAL_FUNC(ACC.FROM_DATE, V_TODAY, ACC.LOCKED_AMOUNT),
            CALC_CBAL_VAL_FUNC(ECB.CURR_ASSET_TYPE, ECB.OPEN_BALANCE, ECB.CREDIT_MVMT, ECB.DEBIT_MVMT),
            CALC_ACCRUE_VAL_FUNC(ECB.CURR_ASSET_TYPE, ECB.OPEN_BALANCE, ECB.CREDIT_MVMT, ECB.DEBIT_MVMT),
            TO_NUMBER(LMT.INTERNAL_AMOUNT),
            ACC.WINDOW_ID,
            ACC.COMMIT_TS,
            ACC.REPLICAT_TS,
            ACC.MAPPED_TS,
            'ACC'
        FROM TABLE(V_WINDOW_ID_LIST) V
        JOIN FMSB_ACC_MAPPED ACC ON ACC.WINDOW_ID = V.COLUMN_VALUE
        JOIN FMSB_ARR_DD ARR ON ARR.LINKED_APPL_ID = ACC.RECID
        JOIN FMSB_ECB_MAPPED ECB ON ECB.RECID = ACC.RECID
        JOIN FMSB_ADL_MAPPED ADL ON ADL.RECID = ARR.RECID
        JOIN FMSB_LMT_MAPPED LMT ON LMT.RECID = ACC.LIMIT_KEY
        LEFT JOIN F_PST_MAPPED PST ON PST.RECID = ACC.POSTING_RESTRICT;

        COMMIT;
    EXCEPTION
        WHEN OTHERS THEN
            ROLLBACK;
            RAISE;
    END GEN_FROM_ACC_PROC;

    PROCEDURE GEN_FROM_ECB_PROC IS
        V_WINDOW_ID_LIST T_WINDOW_ID_ARRAY;
        V_TODAY          VARCHAR2(8);
    BEGIN
        DELETE FROM T24_DDMEMO_ACTIVITY_ECB CDC
        WHERE EXISTS (
            SELECT 1 FROM FMSB_ECB_MAPPED ECB
            WHERE ECB.RECID = CDC.RECID AND CDC.WINDOW_ID <= ECB.WINDOW_ID
        )
        -- AND ROWNUM <= 5000
        RETURNING CDC.WINDOW_ID BULK COLLECT INTO V_WINDOW_ID_LIST;
    
        SELECT TODAY INTO V_TODAY
        FROM F_DAT_MAPPED
        WHERE RECID = 'VN0011000';

        INSERT INTO T24_DDMEMO_ACTIVITY (
            BRANCH, ACCTNO, ACNAME, CIFNO, STATUS, SCCODE,
            DLA7, DLA6, HOLD, CBAL, ACCRUE, ODLIMT,
            WINDOW_ID, COMMIT_TS, REPLICAT_TS, MAPPED_TS, CALL_CDC
        )
        SELECT
            ACC.CO_CODE,
            TO_NUMBER(ECB.RECID),
            TRIM(ACC.ACNAME),
            TO_NUMBER(ACC.CUSTOMER),
            CASE
                WHEN ARR.ARR_STATUS IN ('CLOSE', 'PENDING.CLOSURE', 'CANCELLED') THEN 2
                WHEN PST.RESTRICTION_TYPE = 'DEBIT' THEN 6
                WHEN PST.RESTRICTION_TYPE = 'ALL' THEN 7
                WHEN ADL.DORMANCY_STATUS IS NOT NULL THEN 9
                WHEN ARR.START_DATE = V_TODAY AND ARR.ARR_STATUS NOT IN ('CLOSE', 'PENDING.CLOSURE') THEN 4
                WHEN ARR.ARR_STATUS IN ('AUTH', 'RESTORE-AUTH') AND ADL.DORMANCY_STATUS IS NULL THEN 1
            END,
            ARR.ACTIVE_PRODUCT,
            (
                SELECT TO_NUMBER(TO_CHAR(MAX_EFF_DAT, 'YYYYDDD'))
                FROM MV_FMSB_ARC_DDMEMO
                WHERE ARRANGEMENT = ARR.RECID
            ),
            (
                SELECT TO_NUMBER(TO_CHAR(MAX_EFF_DAT, 'DDMMYY'))
                FROM MV_FMSB_ARC_DDMEMO
                WHERE ARRANGEMENT = ARR.RECID
            ),
            CALC_HOLD_VAL_FUNC(ACC.FROM_DATE, V_TODAY, ACC.LOCKED_AMOUNT),
            CALC_CBAL_VAL_FUNC(ECB.CURR_ASSET_TYPE, ECB.OPEN_BALANCE, ECB.CREDIT_MVMT, ECB.DEBIT_MVMT),
            CALC_ACCRUE_VAL_FUNC(ECB.CURR_ASSET_TYPE, ECB.OPEN_BALANCE, ECB.CREDIT_MVMT, ECB.DEBIT_MVMT),
            TO_NUMBER(LMT.INTERNAL_AMOUNT),
            ECB.WINDOW_ID,
            ECB.COMMIT_TS,
            ECB.REPLICAT_TS,
            ECB.MAPPED_TS,
            'ECB'
        FROM TABLE(V_WINDOW_ID_LIST) V
        JOIN FMSB_ECB_MAPPED ECB ON ECB.WINDOW_ID = V.COLUMN_VALUE
        JOIN FMSB_ACC_MAPPED ACC ON ACC.RECID = ECB.RECID
        JOIN FMSB_ARR_DD ARR ON ARR.LINKED_APPL_ID = ECB.RECID
        JOIN FMSB_ADL_MAPPED ADL ON ADL.RECID = ARR.RECID
        JOIN FMSB_LMT_MAPPED LMT ON LMT.RECID = ACC.LIMIT_KEY
        LEFT JOIN F_PST_MAPPED PST ON PST.RECID = ACC.POSTING_RESTRICT;

        COMMIT;
    EXCEPTION
        WHEN OTHERS THEN
            ROLLBACK;
            RAISE;
    END GEN_FROM_ECB_PROC;

    PROCEDURE GEN_FROM_ARR_PROC IS
        V_WINDOW_ID_LIST T_WINDOW_ID_ARRAY;
        V_TODAY          VARCHAR2(8);
    BEGIN
        DELETE FROM T24_DDMEMO_ACTIVITY_ARR CDC
        WHERE EXISTS (
            SELECT 1 FROM FMSB_ARR_DD ARR
            WHERE ARR.RECID = CDC.RECID AND CDC.WINDOW_ID <= ARR.WINDOW_ID
        )
        -- AND ROWNUM <= 5000
        RETURNING CDC.WINDOW_ID BULK COLLECT INTO V_WINDOW_ID_LIST;
    
        SELECT TODAY INTO V_TODAY
        FROM F_DAT_MAPPED
        WHERE RECID = 'VN0011000';

        INSERT INTO T24_DDMEMO_ACTIVITY (
            BRANCH, ACCTNO, ACNAME, CIFNO, STATUS, SCCODE,
            DLA7, DLA6, HOLD, CBAL, ACCRUE, ODLIMT,
            WINDOW_ID, COMMIT_TS, REPLICAT_TS, MAPPED_TS, CALL_CDC
        )
        SELECT
            ACC.CO_CODE,
            TO_NUMBER(ARR.LINKED_APPL_ID),
            TRIM(ACC.ACNAME),
            TO_NUMBER(ACC.CUSTOMER),
            CASE
                WHEN ARR.ARR_STATUS IN ('CLOSE', 'PENDING.CLOSURE', 'CANCELLED') THEN 2
                WHEN PST.RESTRICTION_TYPE = 'DEBIT' THEN 6
                WHEN PST.RESTRICTION_TYPE = 'ALL' THEN 7
                WHEN ADL.DORMANCY_STATUS IS NOT NULL THEN 9
                WHEN ARR.START_DATE = V_TODAY AND ARR.ARR_STATUS NOT IN ('CLOSE', 'PENDING.CLOSURE') THEN 4
                WHEN ARR.ARR_STATUS IN ('AUTH', 'RESTORE-AUTH') AND ADL.DORMANCY_STATUS IS NULL THEN 1
            END,
            ARR.ACTIVE_PRODUCT,
            (
                SELECT TO_NUMBER(TO_CHAR(MAX_EFF_DAT, 'YYYYDDD'))
                FROM MV_FMSB_ARC_DDMEMO
                WHERE ARRANGEMENT = ARR.RECID
            ),
            (
                SELECT TO_NUMBER(TO_CHAR(MAX_EFF_DAT, 'DDMMYY'))
                FROM MV_FMSB_ARC_DDMEMO
                WHERE ARRANGEMENT = ARR.RECID
            ),
            CALC_HOLD_VAL_FUNC(ACC.FROM_DATE, V_TODAY, ACC.LOCKED_AMOUNT),
            CALC_CBAL_VAL_FUNC(ECB.CURR_ASSET_TYPE, ECB.OPEN_BALANCE, ECB.CREDIT_MVMT, ECB.DEBIT_MVMT),
            CALC_ACCRUE_VAL_FUNC(ECB.CURR_ASSET_TYPE, ECB.OPEN_BALANCE, ECB.CREDIT_MVMT, ECB.DEBIT_MVMT),
            TO_NUMBER(LMT.INTERNAL_AMOUNT),
            ARR.WINDOW_ID,
            ARR.COMMIT_TS,
            ARR.REPLICAT_TS,
            ARR.MAPPED_TS,
            'ARR'
        FROM TABLE(V_WINDOW_ID_LIST) V
        JOIN FMSB_ARR_DD ARR ON ARR.WINDOW_ID = V.COLUMN_VALUE
        JOIN FMSB_ACC_MAPPED ACC ON ACC.RECID = ARR.LINKED_APPL_ID
        JOIN FMSB_ECB_MAPPED ECB ON ECB.RECID = ARR.LINKED_APPL_ID
        JOIN FMSB_ADL_MAPPED ADL ON ADL.RECID = ARR.RECID
        JOIN FMSB_LMT_MAPPED LMT ON LMT.RECID = ACC.LIMIT_KEY
        LEFT JOIN F_PST_MAPPED PST ON PST.RECID = ACC.POSTING_RESTRICT;

        COMMIT;
    EXCEPTION
        WHEN OTHERS THEN
            ROLLBACK;
            RAISE;
    END GEN_FROM_ARR_PROC;

    PROCEDURE GEN_FROM_LMT_PROC IS
        V_WINDOW_ID_LIST T_WINDOW_ID_ARRAY;
        V_TODAY          VARCHAR2(8);
    BEGIN
        DELETE FROM T24_DDMEMO_ACTIVITY_LMT CDC
        WHERE EXISTS (
            SELECT 1 FROM FMSB_LMT_MAPPED LMT
            WHERE LMT.RECID = CDC.RECID AND CDC.WINDOW_ID <= LMT.WINDOW_ID
        )
        -- AND ROWNUM <= 5000
        RETURNING CDC.WINDOW_ID BULK COLLECT INTO V_WINDOW_ID_LIST;
    
        SELECT TODAY INTO V_TODAY
        FROM F_DAT_MAPPED
        WHERE RECID = 'VN0011000';

        INSERT INTO T24_DDMEMO_ACTIVITY (
            BRANCH, ACCTNO, ACNAME, CIFNO, STATUS, SCCODE,
            DLA7, DLA6, HOLD, CBAL, ACCRUE, ODLIMT,
            WINDOW_ID, COMMIT_TS, REPLICAT_TS, MAPPED_TS, CALL_CDC
        )
        SELECT
            ACC.CO_CODE,
            TO_NUMBER(ACC.RECID),
            TRIM(ACC.ACNAME),
            TO_NUMBER(ACC.CUSTOMER),
            CASE
                WHEN ARR.ARR_STATUS IN ('CLOSE', 'PENDING.CLOSURE', 'CANCELLED') THEN 2
                WHEN PST.RESTRICTION_TYPE = 'DEBIT' THEN 6
                WHEN PST.RESTRICTION_TYPE = 'ALL' THEN 7
                WHEN ADL.DORMANCY_STATUS IS NOT NULL THEN 9
                WHEN ARR.START_DATE = V_TODAY AND ARR.ARR_STATUS NOT IN ('CLOSE', 'PENDING.CLOSURE') THEN 4
                WHEN ARR.ARR_STATUS IN ('AUTH', 'RESTORE-AUTH') AND ADL.DORMANCY_STATUS IS NULL THEN 1
            END,
            ARR.ACTIVE_PRODUCT,
            (
                SELECT TO_NUMBER(TO_CHAR(MAX_EFF_DAT, 'YYYYDDD'))
                FROM MV_FMSB_ARC_DDMEMO
                WHERE ARRANGEMENT = ARR.RECID
            ),
            (
                SELECT TO_NUMBER(TO_CHAR(MAX_EFF_DAT, 'DDMMYY'))
                FROM MV_FMSB_ARC_DDMEMO
                WHERE ARRANGEMENT = ARR.RECID
            ),
            CALC_HOLD_VAL_FUNC(ACC.FROM_DATE, V_TODAY, ACC.LOCKED_AMOUNT),
            CALC_CBAL_VAL_FUNC(ECB.CURR_ASSET_TYPE, ECB.OPEN_BALANCE, ECB.CREDIT_MVMT, ECB.DEBIT_MVMT),
            CALC_ACCRUE_VAL_FUNC(ECB.CURR_ASSET_TYPE, ECB.OPEN_BALANCE, ECB.CREDIT_MVMT, ECB.DEBIT_MVMT),
            TO_NUMBER(LMT.INTERNAL_AMOUNT),
            LMT.WINDOW_ID,
            LMT.COMMIT_TS,
            LMT.REPLICAT_TS,
            LMT.MAPPED_TS,
            'LMT'
        FROM TABLE(V_WINDOW_ID_LIST) V
        JOIN FMSB_LMT_MAPPED LMT ON LMT.WINDOW_ID = V.COLUMN_VALUE
        JOIN FMSB_ACC_MAPPED ACC ON ACC.LIMIT_KEY = LMT.RECID
        JOIN FMSB_ECB_MAPPED ECB ON ECB.RECID = ACC.RECID        
        JOIN FMSB_ARR_DD ARR ON ARR.LINKED_APPL_ID = ACC.RECID
        JOIN FMSB_ADL_MAPPED ADL ON ADL.RECID = ARR.RECID
        LEFT JOIN F_PST_MAPPED PST ON PST.RECID = ACC.POSTING_RESTRICT;

        COMMIT;
    EXCEPTION
        WHEN OTHERS THEN
            ROLLBACK;
            RAISE;
    END GEN_FROM_LMT_PROC

    PROCEDURE GEN_FROM_ADL_PROC IS
        V_WINDOW_ID_LIST T_WINDOW_ID_ARRAY;
        V_TODAY          VARCHAR2(8);
    BEGIN
        DELETE FROM T24_DDMEMO_ACTIVITY_ADL CDC
        WHERE EXISTS (
            SELECT 1 FROM FMSB_ADL_MAPPED ADL
            WHERE ADL.RECID = CDC.RECID AND CDC.WINDOW_ID <= ADL.WINDOW_ID
        )
        -- AND ROWNUM <= 5000
        RETURNING CDC.WINDOW_ID BULK COLLECT INTO V_WINDOW_ID_LIST;
    
        SELECT TODAY INTO V_TODAY
        FROM F_DAT_MAPPED
        WHERE RECID = 'VN0011000';

        INSERT INTO T24_DDMEMO_ACTIVITY (
            BRANCH, ACCTNO, ACNAME, CIFNO, STATUS, SCCODE,
            DLA7, DLA6, HOLD, CBAL, ACCRUE, ODLIMT,
            WINDOW_ID, COMMIT_TS, REPLICAT_TS, MAPPED_TS, CALL_CDC
        )
        SELECT
            ACC.CO_CODE,
            TO_NUMBER(ARR.LINKED_APPL_ID),
            TRIM(ACC.ACNAME),
            TO_NUMBER(ACC.CUSTOMER),
            CASE
                WHEN ARR.ARR_STATUS IN ('CLOSE', 'PENDING.CLOSURE', 'CANCELLED') THEN 2
                WHEN PST.RESTRICTION_TYPE = 'DEBIT' THEN 6
                WHEN PST.RESTRICTION_TYPE = 'ALL' THEN 7
                WHEN ADL.DORMANCY_STATUS IS NOT NULL THEN 9
                WHEN ARR.START_DATE = V_TODAY AND ARR.ARR_STATUS NOT IN ('CLOSE', 'PENDING.CLOSURE') THEN 4
                WHEN ARR.ARR_STATUS IN ('AUTH', 'RESTORE-AUTH') AND ADL.DORMANCY_STATUS IS NULL THEN 1
            END,
            ARR.ACTIVE_PRODUCT,
            (
                SELECT TO_NUMBER(TO_CHAR(MAX_EFF_DAT, 'YYYYDDD'))
                FROM MV_FMSB_ARC_DDMEMO
                WHERE ARRANGEMENT = ARR.RECID
            ),
            (
                SELECT TO_NUMBER(TO_CHAR(MAX_EFF_DAT, 'DDMMYY'))
                FROM MV_FMSB_ARC_DDMEMO
                WHERE ARRANGEMENT = ARR.RECID
            ),
            CALC_HOLD_VAL_FUNC(ACC.FROM_DATE, V_TODAY, ACC.LOCKED_AMOUNT),
            CALC_CBAL_VAL_FUNC(ECB.CURR_ASSET_TYPE, ECB.OPEN_BALANCE, ECB.CREDIT_MVMT, ECB.DEBIT_MVMT),
            CALC_ACCRUE_VAL_FUNC(ECB.CURR_ASSET_TYPE, ECB.OPEN_BALANCE, ECB.CREDIT_MVMT, ECB.DEBIT_MVMT),
            (LMT.INTERNAL_AMOUNT),
            ADL.WINDOW_ID,
            ADL.COMMIT_TS,
            ADL.REPLICAT_TS,
            ADL.MAPPED_TS,
            'ADL'
        FROM TABLE(V_WINDOW_ID_LIST) V
        JOIN FMSB_ADL_MAPPED ADL ON ADL.WINDOW_ID = V.COLUMN_VALUE
        JOIN FMSB_ARR_DD ARR ON ARR.RECID = ADL.RECID
        JOIN FMSB_ACC_MAPPED ACC ON ACC.RECID = ARR.LINKED_APPL_ID
        JOIN FMSB_ECB_MAPPED ECB ON ECB.RECID = ARR.LINKED_APPL_ID
        JOIN FMSB_LMT_MAPPED LMT ON LMT.RECID = ACC.LIMIT_KEY
        LEFT JOIN F_PST_MAPPED PST ON PST.RECID = ACC.POSTING_RESTRICT;

        COMMIT;
    EXCEPTION
        WHEN OTHERS THEN
            ROLLBACK;
            RAISE;
    END GEN_FROM_ADL_PROC;
    
END T24_DDMEMO_ACTIVITY_PKG;
